### ISSUE TITLE
Resource not found error running tests for creating new alert

### ISSUE THREAD

**Issue by RubyLi0612** [terraform-providers/terraform-provider-newrelic#10]
### Terraform Version
Terraform v0.9.8

### Affected Resource(s)
newrelic_alert_condition
newrelic_alert_channel

### Terraform Configuration Files
```hcl
resource "newrelic_alert_policy" "foo" {
  name = "tf-test-nrql-%[1]s"
}

resource "newrelic_alert_condition" "foo" {
  policy_id = "${newrelic_alert_policy.foo.id}"
  name            = "tf-test-nrql-%[1]s"
  type            = "nrql_query"
  runbook_url     = "https://foo.example.com"

  term {
    duration      = 5
    operator      = "below"
    priority      = "critical"
    threshold     = "0.75"
    time_function = "all"
  }

  nrql {
    query = "SELECT count(*) from SyntheticCheck where monitorName = 'foo' and result != 'SUCCESS'"
    since_value = 3
  }

  value_function = "single_value"
}
```

### Debug Output
[https://gist.github.com/RubyLi0612/0c5922d1bc90fcef66c586e9efe7667a](url)

### Expected Behavior
Pass tests for creating new NewRelic alert conditions of type NRQL query.

### Actual Behavior
outputed when running `github.com/terraform-providers/terraform-provider-newrelic/newrelic/resource_newrelic_alert_condition_test.go`: Step 2 error: Check failed: Check 1/13 error: newrelic: Resource not found
newrelic_alert_policy_channel.foo: Alerts policy 87391 could not be found.

### Steps to Reproduce
Added implementations for NRQL query NewRelic alert condition inside `github.com/terraform-providers/terraform-provider-newrelic/newrelic/resource_newrelic_alert_condition.go`
Added test for NRQL query NewRelic alert condition inside `github.com/terraform-providers/terraform-provider-newrelic/newrelic/resource_newrelic_alert_condition_test.go`.
`cd /github.com/terraform-providers/terraform-provider-newrelic/`
`make fmt`
`make testacc`

### Important Factoids
New condition type for NRQL is implemented in `github.com/terraform-providers/terraform-provider-newrelic/newrelic/resource_newrelic_alert_condition.go`
Used the same policy and condition resource as originally in test files to test newly implemented features.
NEWRELIC_API_KEY and NEWRELIC_LICENSE_KEY  are set correctly according to my NewRelic account.

**Comment by ctrombley** [comment]
Addressed in #58.
