### ISSUE TITLE
newrelic_alert_condition fails when no infrastructure exists in account

### ISSUE THREAD

**Issue by AshleyPoole** [terraform-providers/terraform-provider-newrelic#118]
### Terraform Version
Terraform v0.11.11
+ provider.newrelic v1.4.0

### Affected Resource(s)
newrelic_alert_condition

### Terraform Configuration Files
```hcl
resource "newrelic_infra_alert_condition" "host_not_reporting" {
  policy_id = "${newrelic_alert_policy.infra_policy.id}"

  name       = "Host Not Reporting"
  type       = "infra_host_not_reporting"

  critical {
    duration      = 5
  }
}
```

### Debug Output
https://gist.github.com/AshleyPoole/c4e8a9f47260e3fb16a501745082d7df

### Expected Behavior
Alert condition is created but allocated against no resources.

### Actual Behavior
Received an error instead as couldn't parse empty entries.
`newrelic_alert_condition.apdex: entities.0: cannot parse '' as int: strconv.ParseInt: parsing "": invalid syntax`

### Steps to Reproduce
1. `terraform plan`

### Important Factoids
No infrastructure exist in New Relic when running the plan.

**Comment by ctrombley** [comment]
Confirmed working in Terraform v0.12.13 and v1.5.2 of the provider.
