### ISSUE TITLE
Terms threshold reported blank when assigning zero to it

### ISSUE THREAD

**Issue by RubyLi0612** [terraform-providers/terraform-provider-newrelic#12]
### Terraform Version
Terraform v0.9.11

### Affected Resource(s)
newrelic_alert_condition

### Terraform Configuration Files
```hcl
# Configure the New Relic provider
provider "newrelic" {
  api_key = "${var.newrelic_api_key}"
}

resource "newrelic_alert_policy" "alert" {
  name = "Policy"
}
```

### Expected Behavior
Assign threshold of the condition to 0 successfully.

### Actual Behavior
Error outputed as: Terms threshold can't be blank
![image](https://user-images.githubusercontent.com/29551647/27975896-0e659f50-6319-11e7-8121-1edd6ddb5fb4.png)

### Steps to Reproduce
 `terraform apply`

### Important Factoids
According to the documentation for terraform newrelic_alert_condition, threshold can be set to 0: 
![image](https://user-images.githubusercontent.com/29551647/27975947-4402b486-6319-11e7-9136-0d4a669fa2bd.png)
Yet assigning it to "0", 0, "0.0" all trigger the error.

**Comment by grubernaut** [comment]
Upstream bug, submitted issue for a fix.

**Comment by RubyLi0612** [comment]
Hi. Thank you for fixing the issue. I tried the updated newest version of this provider (also included the newest paultyng/go-newrelic) by creating some NewRelic conditions. There were no more error reporting on this issue. However, when I get onto my NewRelic account to view them, I found that one APM BROWSER APPLICATION METRIC condition showed blank in the threshold box, which was set to "0" in terraform:
![screen shot 2017-07-12 at 3 45 00 pm](https://user-images.githubusercontent.com/29551647/28143287-9f4556d8-6719-11e7-97e9-5444983f73dc.png)
![screen shot 2017-07-12 at 3 44 49 pm](https://user-images.githubusercontent.com/29551647/28143297-aae0c72a-6719-11e7-8aad-ae05bcb8c1da.png)

Yet another APM APPLICATION METRIC condition went fine. I'm guessing that there remains some issue for different types?

**Comment by grubernaut** [comment]
Hey @RubyLi0612, sorry you're still having an issue. 

The fix above was only for the `threshold` attribute inside the `terms` configuration. 
Can you elaborate on what you mean by: 
> I'm guessing that there remains some issue for different types?

Thanks!

**Comment by RubyLi0612** [comment]
Sorry for the confusion. I meant to say that the `threshold` attribute inside the `terms` configuration for a browser application metric condition I created seems not working. It is supposed to show 0 when I set 0 through terraform, but showed empty entry instead. However, apm application metric condition is correct.
