### ISSUE TITLE
newrelic_infra_alert_condition not saving state leading to duplicate resources

### ISSUE THREAD

**Issue by ryandzink** [terraform-providers/terraform-provider-newrelic#129]
### Terraform Version
Terraform v0.11.13
provider.newrelic v1.5.0

### Affected Resource(s)
newrelic_infra_alert_condition

This issue seems to affect multiple resources, but always newrelic_infra_alert_condition resources. I have a large set of ~300 new relic resources I'm applying. The first time I apply, the resources are all created as expected. However, another apply prompts me to create 6 new resources, which will duplicate existing resources. If I create them and then apply again, a different set of 6 resources will be created. This happens indefinitely, but always a set of 6 resources are prompted for creation (always creating duplicate resources).

### Terraform Configuration Files
An example of a resource where this happens:
```hcl
resource "newrelic_infra_alert_condition" "rabbitmq_server_offline" {
  policy_id = "${newrelic_alert_policy.application_infra_info.id}"
  name      = "RabbitMQ server offline"
  type      = "infra_host_not_reporting"
  where     = "(`hostname` LIKE '%${var.rabbitmq_server_hostname_pattern[local.env]}%')"

  critical {
    duration      = 5
    time_function = "all"
  }

  lifecycle {
    ignore_changes = ["critical.0.time_function"]
  }
}
```

### Debug Output
I see the following output in the debug logs when doing a terraform apply targeting this resource: 
```
2019/04/10 14:48:56 [DEBUG] Resource state not found for "newrelic_infra_alert_condition.rabbitmq_server_offline": newrelic_infra_alert_condition.rabbitmq_server_offline
2019-04-10T14:48:56.813-0700 [DEBUG] plugin.terraform-provider-newrelic_v1.5.0_x4: 2019/04/10 14:48:56 [DEBUG] Instance Diff is nil in Diff()
2019/04/10 14:48:56 [DEBUG] Resource state not found for "newrelic_infra_alert_condition.rabbitmq_server_offline": newrelic_infra_alert_condition.rabbitmq_server_offline
2019/04/10 14:48:56 [TRACE] Graph after step *terraform.AttachStateTransformer:
newrelic_infra_alert_condition.rabbitmq_server_offline - *terraform.NodePlannableResourceInstance
2019/04/10 14:48:56 [TRACE] Graph after step *terraform.TargetsTransformer:
newrelic_infra_alert_condition.rabbitmq_server_offline - *terraform.NodePlannableResourceInstance
2019/04/10 14:48:56 [DEBUG] ReferenceTransformer: "newrelic_infra_alert_condition.rabbitmq_server_offline" references: []
2019/04/10 14:48:56 [DEBUG] command: asking for input: "Do you want to perform these actions in workspace \"prod\"?"
```

If I choose to apply the change, it will be created, but will duplicate already existing resources, so I will have two alert conditions with the same configuration and name.

I believe the issue may be related to the initial apply not creating state correctly... running `terraform state show newrelic_infra_alert_condition.rabbitmq_server_offline` returns nothing, which would then make the recreation of the resources make sense.

Interestingly, if I do a `terraform destroy` targeting the resource, it removes all duplicates when it is destroyed, so there is some awareness that there are duplicate resources being created.

### Expected Behavior
After the initial `terraform apply`, nothing should happen and no resources should get created.

### Actual Behavior
Duplicate resources are created.

### Steps to Reproduce
1. `terraform apply`

### Notes
My remote state is being stored in an S3 bucket.

**Comment by ryandzink** [comment]
I spoke to New Relic support about this and they indicated that this is an issue because the go-newrelic library being used by the provider doesn't use the **limit** and **offset** parameters mentioned here: https://docs.newrelic.com/docs/infrastructure/new-relic-infrastructure/infrastructure-alert-conditions/rest-api-calls-new-relic-infrastructure-alerts#get-conditions and can't handle very large sets of infrastructure alert conditions as a result.

I'm creating a PR on that repo to hopefully implement that there.

**Comment by zlesnr** [comment]
Hi @ryandzink, apologies for the slow response here.  Can you confirm this is still an issue?  I know there were some recent plumbing changes with respect to the underlying Go client, and I suspect this may have been fixed by those changes.  If this is still an issue, we can dig in a bit more.

**Comment by ryandzink** [comment]
Hi @zlesnr , no it looks like this is no longer an issue, I wasn't aware that changes were made to the Go client but I am now able to manage several hundred New Relic resources with none of these symptoms. I'll go ahead and close the issue.

**Comment by zlesnr** [comment]
Great, thanks for coming back to let us know @ryandzink.
