### ISSUE TITLE
newrelic_alert_channel with slack always recreate resources

### ISSUE THREAD

**Issue by sonots** [terraform-providers/terraform-provider-newrelic#130]
version

```
$ terraform -version
Terraform v0.11.13
+ provider.newrelic v1.5.0
```

```
resource "newrelic_alert_channel" "slack" {
  name = "slack"
  type = "slack"

  configuration = {
    channel = "test"
    url     = "https://hooks.slack.com/services/xxxx/xxxxx"
  }
}
```

This always destroy/create on `terraform apply` repeatedly without any modifications.

```
-/+ newrelic_alert_channel.slack (new resource required)
      id:                    "2344397" => <computed> (forces new resource)
      configuration.%:       "1" => "2" (forces new resource)
      configuration.channel: <sensitive> => <sensitive> (attribute changed)
      configuration.url:     <sensitive> => <sensitive> (forces new resource)
      name:                  "slack" => "slack"
      type:                  "slack" => "slack"
```

**Comment by JacobJohansen** [comment]
```
  lifecycle {
    ignore_changes = ["configuration"]
  }
```
its because it has sensitive data in it and doesn't know when it changes

**Comment by sonots** [comment]
Thanks! It worked.

**Comment by pickgr** [comment]
@ctrombley would you mind reviewing this?  I'm not sure if the ignore_changes work-around above should be necessary.  Maybe this can be re-opened?  At the very least, it might be nice to add this to the documentation.

**Comment by ctrombley** [comment]
@pickgr The issue here is that the underlying API intentionally hides the secrets that were configured when the resource has been provisioned, so terraform thinks there is a diff.  I'll make a note and we will get this in the docs.
