### ISSUE TITLE
Documentation for resource: newrelic_synthetics_monitor and newrelic_synthetics_monitor_script

### ISSUE THREAD

**Issue by pickgr** [terraform-providers/terraform-provider-newrelic#138]
I believe support was added here:

https://github.com/terraform-providers/terraform-provider-newrelic/commit/ac32fcfb9611149aa1fbadfc6edf0a5671babc10

but is missing from the documentation at

https://www.terraform.io/docs/providers/newrelic/

**Comment by brasey** [comment]
I'm also looking for these docs.

**Comment by ctrombley** [comment]
Documentation is available at the following public URLs:
https://www.terraform.io/docs/providers/newrelic/r/synthetics_monitor.html
https://www.terraform.io/docs/providers/newrelic/r/synthetics_monitor_script.html
