### ISSUE TITLE
newrelic_alert_channel with type=user is invalid

### ISSUE THREAD

**Issue by pickgr** [terraform-providers/terraform-provider-newrelic#139]
### Terraform Version
Terraform v0.11.11
+ provider.newrelic v1.5.0

### Affected Resource(s)
newrelic_alert_channel

### Terraform Configuration Files
```hcl
resource "newrelic_alert_channel" "user_john" {
  name = "user_john"
  type = "user"

  configuration = {
    user_id = "john"
  }
}
```

### Debug Output
newrelic_alert_channel.user_john: Creating...
  configuration.%:       "" => "1"
  configuration.user_id: "<sensitive>" => "<sensitive>"
  name:                  "" => "user_john"
  type:                  "" => "user"
Releasing state lock. This may take a few moments...

Error: Error applying plan:

1 error(s) occurred:

* newrelic_alert_channel.user_john: 1 error(s) occurred:

* newrelic_alert_channel.user_john: Invalid channel type

### Expected Behavior
New alert channel of type user should be created successfully.

### Actual Behavior
See output above

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan` (works OK)
2. `terraform apply` (fails)

### Important Factoids
I do see a reference in the code here:

https://github.com/terraform-providers/terraform-provider-newrelic/blob/master/newrelic/resource_newrelic_alert_channel.go#L41

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? 
Not aware of any, but the documentation also does not list it.

**Comment by bkimbrough-bw** [comment]
I don't think this is quite right as it seems each user that is setup automatically can receive alerts and I wouldn't want to use alerts to create users. However having a data provider to get that user so that I can link it on the newrelic_alert_policy_channel would be a great add to this.

**Comment by ctrombley** [comment]
User channels cannot be created since New Relic users cannot currently be provisioned with terraform.  A data source for alert channels of type `user` sounds feasible, however.  I'll create a new issue to track this enhancement request.
