### ISSUE TITLE
Repo maintainers

### ISSUE THREAD

**Issue by AshleyPoole** [terraform-providers/terraform-provider-newrelic#140]
It seems like there isn't enough repo maintainers to approve PRs and keep things moving. Is there a possiblity to accept a couple of maintainers from the community to help?

**Comment by AshleyPoole** [comment]
@paultyng

**Comment by paultyng** [comment]
A few people from New Relic (@lars2893) were maintaining this, I only check in every once in a while as I was the initial creator of the provider and still own the SDK repo, but I don't do anything with New Relic currently, so hard to know what people want and/or need or understand use cases on newer features.

I'm happy to add additional community maintainers. Please email me at ptyng@hashicorp.com and we start the process to add you to the repo.

**Comment by paultyng** [comment]
@ianrayns similarly, please email me if interested.
