### ISSUE TITLE
Enhancement request: Synthetic monitor failure to include entity and threshold

### ISSUE THREAD

**Issue by thatguylong** [terraform-providers/terraform-provider-newrelic#143]
### Enhancement Request
Synthetics monitor failure support for adding entity and thresholds.

### Expected Behavior
The ability to configure synthetics monitor failures that include entity IDs and defined thesholds.

### Actual Behavior
Not currently supported.

### Steps to Reproduce
https://www.terraform.io/docs/providers/newrelic/index.html is lacking and so is this https://www.terraform.io/docs/providers/newrelic/r/synthetics_alert_condition.html

**Comment by sanderblue** [comment]
Hi there, for the long delay in response. We're not quite sure what the request is here. Are you wanting to see which entities triggered the alert as a form of the alert's "metadata"? If that's the case, this would involve changes to upstream APIs and it might be better to submit a support ticket with [New Relic Support](support.newrelic.com) or by emailing support at support@newrelic.com.
