### ISSUE TITLE
newrelic_dashboard state is not refreshed

### ISSUE THREAD

**Issue by stepankotyk** [terraform-providers/terraform-provider-newrelic#148]
Hi there,

Seems check for existing resources is not working properly on dashboard if resource is removed via NewRelic UI.

### Terraform Version
Tried:
Terraform v0.10.8 
Terraform v0.12.3

### Affected Resource(s)
newrelic_dashboard

### Expected Behavior
state is refreshed

### Actual Behavior
State is not refreshed.
Error: Error refreshing state: 1 error(s) occurred:
* newrelic_dashboard.testing: 1 error(s) occurred:
* newrelic_dashboard.testing: newrelic_dashboard.testing: Dashboard not found

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1.  Create new Dashboard `terraform apply'
2. Remove dashboard on NewRelicUI
3. run `terraform plan`

**Comment by stepankotyk** [comment]
Seems to be similar to this issue
https://github.com/terraform-providers/terraform-provider-newrelic/issues/57

**Comment by ctrombley** [comment]
Fixing this issue relies on https://github.com/paultyng/go-newrelic/pull/73 being merged into the SDK.

**Comment by ctrombley** [comment]
Targeting v1.7.0 for a fix.  Related to #203

**Comment by ctrombley** [comment]
Addressed in paultyng/go-newrelic#73  and #203.
