### ISSUE TITLE
Cannot use widgets that pull data from different accounts

### ISSUE THREAD

**Issue by timleathart** [terraform-providers/terraform-provider-newrelic#154]
Hi team, 

A small feature request: when creating widgets in New Relic dashboards, there is an option to run the `nrql` query on another account than the one containing the dashboard. This functionality exists in the New Relic API:

https://docs.newrelic.com/docs/insights/insights-api/manage-dashboards/insights-dashboard-api#widget-data

and in the New Relic Go client library:

https://github.com/paultyng/go-newrelic/blob/master/api/types.go#L301

so it should just be an easy fix to include this in the terraform provider.

I am happy to make a PR that includes this, but I thought I would add an issue first to check if this functionality wasn't included for a reason first.

**Comment by sad-boy-uoa** [comment]
Hey there, has there been word on this? I'm also running into the same issue

**Comment by ctrombley** [comment]
The underlying SDK [supports the `account_id` parameter](https://github.com/paultyng/go-newrelic/blob/master/api/types.go#L301) so there is no reason we shouldn't be able to use it in the provider.

**Comment by ctrombley** [comment]
I have to walk the above statement back, apologies.  There is an issue with the underlying Dashboards API that does not export these types of widgets, and until that gets some attention we won't be able to support this well in the provider.

**Comment by ctrombley** [comment]
Some more context: https://docs.newrelic.com/docs/insights/insights-api/manage-dashboards/insights-dashboard-api#requirements
