### ISSUE TITLE
newrelic_nrql_alert_condition support for violation_close_timer

### ISSUE THREAD

**Issue by ciscoios** [terraform-providers/terraform-provider-newrelic#157]
Affected Resource(s)

-    newrelic_nrql_alert_condition

Hi all.
Right now, newrelic_alert_condition doesn't supports "**violation_close_timer**" for nrql alerts.
From time to time, we may receive some alerts that can't be closed automatically.
Since we can receive a big amount of alerts it would be better to exclude manual intervention.
I've checked go-newrelic and found that currently there is no support for the "**violation_close_timer**"  parameter.
  https://github.com/paultyng/go-newrelic/blob/6bd4f0fecd759bc18c4806cba51dcb97ecdffbbc/api/types.go#L365

Could you please add this functionality?

**Comment by nrolando46** [comment]
Would like to see this added as well. 

Getting the following when I added within the NRQL Statement 

`nrql {
    query       = "SELECT count(*) from TransactionError where  *
    since_value = "3"
    violation_close_timer = "1"
  }`
`  on main2.tf line 44, in resource "newrelic_nrql_alert_condition" "FetchError":
  44:     violation_close_timer = "1"

An argument named "violation_close_timer" is not expected here.`

**Comment by jordanpurinton** [comment]
Bump

**Comment by jthurman42** [comment]
Closed in #198
