### ISSUE TITLE
As a New Relic Owner for multiple accounts, I would like to manage users and their permissions for each subaccount in code

### ISSUE THREAD

**Issue by JJediny** [terraform-providers/terraform-provider-newrelic#160]
>Github issue template is NA - Feature Request

Similar to how this functionality is supported for other SaaS providers (example):
* https://www.terraform.io/docs/providers/github/d/user.html
* https://www.terraform.io/docs/providers/github/d/team.html

As an New Relic administrator, I would prefer to manage users and their teams/accounts in code to better manage onboarding/offboarding.

**Comment by Claywd** [comment]
@ctrombley I also need this. You guys need contributors or people to help vet PRs?

**Comment by ctrombley** [comment]
@claywd this goes deeper than the provider.  There is a larger body of work in the underlying APIs that is going to need to be undertaken before we can do this.

**Comment by davividal** [comment]
@ctrombley can you please elaborate on that?
I too need this and I would be glad to help.

**Comment by jthurman42** [comment]
This is not currently supported downstream (by the New Relic APIs), with the exception of partnership accounts.  Partnerships are currently not implemented in Terraform and that is being tracked in issue #134 

A feature request for this type of user management has been made internally to New Relic, so until that is completed I'm going to close this out.
