### ISSUE TITLE
Feature request: Synthetic Test labels

### ISSUE THREAD

**Issue by brasey** [terraform-providers/terraform-provider-newrelic#164]
Hi gang! I would like to request adding the ability to label our synthetic tests via Terraform. Currently we can only either do this manually or by sending a request to the NR API.

### Terraform Version
```
Terraform v0.12.7
+ provider.newrelic v1.5.1
```

### Affected Resource(s)
- newrelic_synthetics_monitor

### Expected Behavior
Would like to be able to apply labels to my synthetics monitors as per <https://docs.newrelic.com/docs/apis/synthetics-rest-api/label-examples/use-synthetics-label-apis>

### Actual Behavior
Ain't no labels

**Comment by imsathyakumar** [comment]
+1

**Comment by ebh** [comment]
+1

Anything I can do to help with getting this enhancement done?

**Comment by ctrombley** [comment]
@ebh The first step to getting this implemented is to add [Synthetics labels](https://docs.newrelic.com/docs/apis/synthetics-rest-api/label-examples/use-synthetics-label-apis) as a resource to the existing [new-relic-synthetics-go](https://github.com/dollarshaveclub/new-relic-synthetics-go) client.  There's an additional complication in that the client currently appears to be unmaintained, and we have some plans to fork it or move its functionality into another project.  Regardless, a reference implementation would help us move the needle on this if you'd like to take a stab at it.

**Comment by hieuhoangtrung** [comment]
+1 👍

**Comment by psech** [comment]
+1
That would be a super awesome improvement.

**Comment by veeravallib** [comment]
+1

**Comment by jthurman42** [comment]
The current backend library used for the Synthetics API (github.com/dollarshaveclub/new-relic-synthetics-go ) does not support this feature.  We (New Relic) are currently working on consolidating the backend libraries used as part of this provider, which should unblock this feature request in the near future.

**Comment by zlesnr** [comment]
I think we may be unblocked here.  I'll see if we can line that up soon.

**Comment by zlesnr** [comment]
https://docs.newrelic.com/docs/apis/synthetics-rest-api/label-examples/use-synthetics-label-apis#examples

**Comment by jthurman42** [comment]
Downstream work has been completed newrelic/newrelic-client-go#129
