### ISSUE TITLE
newrelic_nrql_alert_condition doesn't track the actual alert text correctly

### ISSUE THREAD

**Issue by nejoyer** [terraform-providers/terraform-provider-newrelic#167]
### Terraform Version
Terraform v0.12.7
+ provider.newrelic v1.5.1

### Affected Resource(s)
newrelic_nrql_alert_condition

### Terraform Configuration Files
```hcl
provider "newrelic" {
  api_key = "[redacted]"
}

resource "newrelic_alert_policy" "neil_test" {
  name                = "NEILTEST"
  incident_preference = "PER_CONDITION"
}

resource "newrelic_nrql_alert_condition" "neil_test_conidtion" {
  policy_id = "${newrelic_alert_policy.neil_test.id}"
  name      = "neil test name"
  term {
    duration      = "5"
    threshold     = "5"
    operator      = "above"
    priority      = "critical"
    time_function = "all"
  }
  nrql {
    query       = "select count(*) from Transaction"
    since_value = "3"
  }
  value_function = "single_value"
}
```

### Steps to Reproduce
1. `terraform apply`
2. Find the alert condition in the NR UI and modify the condition query to be "select count(*) from Transaction where error is True". Click Save.
3. `terraform plan`

### Expected Behavior
It should show that the condition text that you just edited using the UI will be stomped over by text in the tf file (specifically, the where clause will be deleted)

### Actual Behavior
It says that no changes will be made as the resources are up to date.

### Other Details
If you apply, and there are no other changes, then nothing will happen. But if you edit the name of the condition through the UI, and then do `terraform apply`, it will tell you it is about to change the name, but then will change _both_ the name _and_ the query text.

I think it is related to how the query is written to the state file after getting fetched from the server. When you do an import, the state file doesn't even show the query text (which is a whole 'nother issue and a more complicated repro).

Other changes, like the term.duration are tracked correctly.

### References
Totally different, but also similar: https://github.com/terraform-providers/terraform-provider-newrelic/issues/148

**Comment by ctrombley** [comment]
Addressed in #197

**Comment by zlesnr** [comment]
This no longer looks to be an issue in 1.12.  @nejoyer Following the steps here, the plan does indeed want to change the text back to what is in the manifest.  Can you confirm this is no longer an issue?

**Comment by nejoyer** [comment]
Tested in 1.12.2... seems to work great there. Thank you!
