### ISSUE TITLE
NRQL Alert Threshold of ".99" causes error

### ISSUE THREAD

**Issue by nejoyer** [terraform-providers/terraform-provider-newrelic#168]
### Terraform Version
Terraform v0.12.7
+ provider.newrelic v1.5.1

### Affected Resource(s)
newrelic_nrql_alert_condition

### Terraform Configuration Files
```hcl
provider "newrelic" {
  api_key = "[redacted]"
}

resource "newrelic_alert_policy" "neil_test" {
  name                = "NEILTEST"
  incident_preference = "PER_CONDITION"
}

resource "newrelic_nrql_alert_condition" "neil_test_conidtion" {
  policy_id = "${newrelic_alert_policy.neil_test.id}"
  name      = "neil test name"
  term {
    duration      = "5"
    threshold     = "5"
    operator      = "above"
    priority      = "critical"
    time_function = "all"
  }
  nrql {
    query       = "select count(*) from transaction"
    since_value = "3"
  }
  value_function = "single_value"
}
```

### Steps to Reproduce
1. Create an NRQL alert condition in new relic with a threshold of ".99" (meaning you want to be alerted if the thing happens once.
2. `terraform import newrelic_nrql_alert_condition.neil_test_conidtion [policyid]:[alertconditionid]`

### Expected Behavior
Import should succeed

### Actual Behavior
`Error: json: invalid use of ,string struct tag, trying to unmarshal ".99" into float64`

### Other Details
This error happens on import if *any* of the nrql alert conditions include a threshold of .99 (not just the one you are trying to import).
I suspect this same typing issue would result in lots of other errors too.

### Workaround
Edit your condition using the UI to be "0.99" and then import will succeed.

**Comment by ctrombley** [comment]
This is confirmed working in Terraform v0.12.13 and v1.5.2 of the provider.  Closing.
