### ISSUE TITLE
Support for New Relic Infrastructure

### ISSUE THREAD

**Issue by taharah** [terraform-providers/terraform-provider-newrelic#17]
Currently, none of the API endpoints for creating alerts based on New Relic Infrastructure metrics are supported.

**Comment by Thadir** [comment]
This feature is indeed quite wanted. You want to be able to put everything in the terraform code.

**Comment by rangarb** [comment]
Do we have any forecasted plan for this support..

**Comment by Thadir** [comment]
Isnt it implemented with 1.0.1?

**Comment by smithclay** [comment]
@Thadir Correct, New Relic infrastructure alerts are now supported in 1.0.1.

**Comment by rangarb** [comment]
In NewRelic Infrastructure "Policy" setup, we have "Incident Preference"
attribute on UI which provides option to chose as "By Policy", "By
Condition", "By Condition and entity"..
Can you please help on guiding how should this be done via
terraform-newrelic provider?

Thank you

Regards
Balaji
