### ISSUE TITLE
Feature Request: Alert Condition Entity Labels

### ISSUE THREAD

**Issue by voltechs** [terraform-providers/terraform-provider-newrelic#171]
NewRelic alerts allow for selecting APM entities through labels.
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/1700514/64656970-9eb74980-d3ee-11e9-9482-a4730c8ad25c.png">

### Terraform Version
Terraform v0.11.14
+ provider.aws v1.18.0
+ provider.newrelic v1.5.1
+ provider.null v1.0.0
+ provider.random v2.2.0
+ provider.template v2.1.2

### Affected Resource(s)
- newrelic_alert_condition

I do not currently see a way to do this (0.11 or 0.12).

I do not (currently) keep track of all our applications in Terraform, so explicitly referencing them is cumbersome. The manual alert_conditions currently use labels, and I'd love to pull these resources into Terraform.

**Comment by jthurman42** [comment]
The API endpoint for Alert Conditions does not currently accept labels: https://rpm.newrelic.com/api/explore/alerts_conditions/list

An upstream feature request has been made for this capability.

**Comment by jthurman42** [comment]
Closing this issue until the internal feature request has been completed.
