### ISSUE TITLE
NRQL - Error: We were unable to validate this query

### ISSUE THREAD

**Issue by ishantkumar** [terraform-providers/terraform-provider-newrelic#174]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.12.9

### Affected Resource(s)
NRQL condition

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
N/A
```

### Expected Behavior
NRQL should be success .

### Actual Behavior
Error: We were unable to validate this query. Please see the documentation for more information.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

I am running a query e.g.

`SELECT percentile(duration *1000, 99) FROM Transaction WHERE appName = '<SomeAppName>' and name in ('WebTransaction/RestWebService/files/{path:[^\\:]+} (PUT)') and httpResponseCode != '504' FACET appName" `

On running `terraform apply` ,  it is showing 
`Error: We were unable to validate this query. Please see the documentation for more information.`

**Comment by ctrombley** [comment]
@ishantkumar I believe it is the escaped backslash`\\` in the `{path:[^\\:]+}` section that is causing the API request to fail validation.  NRQL does not support regex matching, but does support wildcard matching as described in [the docs](https://docs.newrelic.com/docs/query-data/nrql-new-relic-query-language/getting-started/nrql-syntax-components-functions).
