### ISSUE TITLE
TF_LOG=DEBUG hangs provider

### ISSUE THREAD

**Issue by morganchristiansson** [terraform-providers/terraform-provider-newrelic#184]
### Terraform Version
Terraform v0.12.12
+ provider.newrelic v1.5.2

### Affected Resource(s)
Please list the resources as a list, for example:
- newrelic_alert_policy_channel

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
provider newrelic {
  api_key = "xxxxxxxxxxxxxxxxxxxxxxxxx"
}

resource newrelic_alert_policy policy {
  name = "policy"
}

resource newrelic_alert_channel alerting {
  name = "PagerDuty"
  type = "pagerduty"

  configuration = {
    service_name = "New Relic"
    service_key = "xxxxxxxxxxxxxxxxxxxxxxxxx"
  }
}

resource newrelic_alert_policy_channel alerting {
  policy_id  = newrelic_alert_policy.policy.id
  channel_id = newrelic_alert_channel.alerting.id
}
```

### Debug Output
```
2019/10/31 20:04:29 [TRACE] dag/walk: vertex "provider.newrelic (close)" is waiting for "newrelic_alert_policy_channel.alerting"
2019/10/31 20:04:34 [TRACE] dag/walk: vertex "provider.newrelic (close)" is waiting for "newrelic_alert_policy_channel.alerting"
2019/10/31 20:04:39 [TRACE] dag/walk: vertex "provider.newrelic (close)" is waiting for "newrelic_alert_policy_channel.alerting"
2019/10/31 20:04:44 [TRACE] dag/walk: vertex "provider.newrelic (close)" is waiting for "newrelic_alert_policy_channel.alerting"
2019/10/31 20:04:49 [TRACE] dag/walk: vertex "provider.newrelic (close)" is waiting for "newrelic_alert_policy_channel.alerting"
```
is printed indeinitely at end of run.. every 5 seconds.

### Expected Behavior
terraform does not hang and completes normally.

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. update `provider.api_key`. `newrelic_alert_channel.configuration.service_key` can be set to any value.
2. `terraform apply` - completes normally
3. `terraform plan` - now hanging
4. `terraform state rm newrelic_alert_policy_channel.alerting` - remove policy channel from state to recover
5. `terrafrom plan` - now works
6. repeat from step 2

**Comment by ctrombley** [comment]
@morganchristiansson I am having trouble reproducing this error.  Can you reach out to support@newrelic.com where they will gather some more context about your issue?

**Comment by morganchristiansson** [comment]
@ctrombley I have reported it as support case 375094 and it has been assigned to the engineers.

The following curl query reproduces the bug. The JSON is correct but the frontend shows an incorrect `(1=1) AND provider='K8sPodSample'` where clause in the frontend and shows no matching datapoints.

```curl -XPOST -H 'X-Api-Key: xxxxxxxxxxxxxxx' -H 'Content-Type: application/json' https://infra-api.newrelic.com/v2/alerts/conditions -d '
{
"data": {
"type": "infra_metric",
"name": "terraform-bugtest",
"enabled": true,
"where_clause": "1=1",
"policy_id": 502701,
"event_type": "K8sPodSample",
"select_value": "isScheduled",
"comparison": "equal",
"critical_threshold": {
"value": 0,
"duration_minutes": 1
}
}
}
'
```

**Comment by morganchristiansson** [comment]
It happens when setting TF_LOG=debug in above example. It's plain terraform apply is just re-creating the resources now. Pretty sure that hung too previously.

As part of larger terraform it hangs in refresh state.

I will open another case with support for this.

**Comment by rjwester** [comment]
I would just like to add that I see this issue when TF_LOG is set to anything except an empty string

**Comment by sanderblue** [comment]
Hi there, just wanted to touch base. Expect some traction on this coming up over next week or two. We're in the process of migrating the provider to our new Go client, `newrelic-client-go`, which will hopefully resolve this.

**Comment by zlesnr** [comment]
Using the latest provider and the example above, with `TF_LOG=DEBUG` set, I do not get hangs following the steps listed above.  @morganchristiansson are you still seeing this issue?

**Comment by sanderblue** [comment]
Also confirming that I cannot reproduce the issue anymore. We've made a lot of updates since this was filed. Since we haven't heard back in a while, we can only assume this is no longer an issue for you. If you come across this bug again, please feel free to open a new issue with steps to reproduce. Thanks for taking the time to report.

**Comment by morganchristiansson** [comment]
I've not had chance to confirm it's fixed sorry - but I have seen all the work you've been putting in and planning to use more shortly. Thanks guys!

**Comment by morganchristiansson** [comment]
So I had a chance to follow up and was able to complete all my terraform code without issues.

Fantastic work guys, thank you.

Next I'll be able to create reusable modules for my monitoring..

**Comment by jthurman42** [comment]
Great to hear, thanks for circling back.  We've also started an initial reusable module and would love feedback on it, or if you have reusable use-cases for us to look at.  You can find the official module here: https://registry.terraform.io/modules/newrelic/apm/newrelic/  (or on GitHub: https://github.com/newrelic/terraform-newrelic-apm/ )
