### ISSUE TITLE
Cannot create newrelic_alert_condition due to absence of violation_close_timer

### ISSUE THREAD

**Issue by RSaundersonDeloitte** [terraform-providers/terraform-provider-newrelic#19]
Hi there,

### Terraform Version
I'm using Terraform v0.10.6

### Affected Resource(s)
- newrelic_alert_condition

### Terraform Configuration Files
```resource "newrelic_alert_condition" "some_threadpool_alert_condition" {
  policy_id                   = "${newrelic_alert_policy.some_threadpool_alert_policy.id}"
  name                        = "${upper(terraform.workspace)}_Some_Threads"
  type                        = "apm_app_metric"
  entities                    = ["${data.newrelic_application.some_app.id}"]
  metric                      = "user_defined"
  condition_scope             = "instance"
  user_defined_metric         = "JmxBuiltIn/ThreadPool/\"some-thread-pool\"/Active"
  user_defined_value_function = "average"

  term {
    duration      = 5
    operator      = "above"
    priority      = "warning"
    threshold     = "150"
    time_function = "all"
  }

  term {
    duration      = 5
    operator      = "above"
    priority      = "critical"
    threshold     = "170"
    time_function = "all"
  }
}
```

### Expected Behaviour
The terraform plan came back clean, so I was not expecting any issues when running the apply.  The apply should have created the newrelic_alert_condition.

### Actual Behaviour
All other terraform new relic resources were created correctly, but all of my newrelic_alert_condition resources failed with the message 

```* newrelic_alert_condition.some_threadpool_alert_condition: 1 error(s) occurred: newrelic_alert_condition.some_threadpool_alert_condition: `violation_close_timer` (in hours) must be present and one of: 1, 2, 4, 8, 12, 24.```

I attempted to add violation_close_timer to the config, thinking that it was a config parameter that I missed off, but when I reran plan I got this message:
```newrelic_alert_condition.some_threadpool_alert_condition: : invalid or unknown key: violation_close_timer```

I then attempted to add violation_close_timer inside the term declaration, but when I reran the plan I got this message:

```newrelic_alert_condition.some_threadpool_alert_condition: term.0: invalid or unknown key: violation_close_timer```

### Steps to Reproduce
1. `terraform apply`

**Comment by ryangardner** [comment]
This error only happens if you are creating an alert of the per-instance type (the `condition_scope: "instance"`) part.

I dove into this a little to see if I could fix it, but it seems that the "violation_close_timer" field isn't implemented in the newrelic api that this provider is based on  (isn't in the types.go there, at least that I could find, even after I updated it to the latest version) so I stopped trying to look for a quick fix for this and tweaked my alerts to not be instance-based (for now).

**Comment by paultyng** [comment]
@ryangardner the API implementation is a pretty thin wrapper, if you want to add a PR [over there](https://github.com/paultyng/go-newrelic) I can get it merged in and another version cut with that field.

**Comment by RSaundersonDeloitte** [comment]
@ryangardner - I'm not sure that not using instance-based alerts really helps me - I'm trying to alert on the thread pool utilisation within a JVM.  I'm pretty sure I have to use instance-based alerts for that.

**Comment by RSaundersonDeloitte** [comment]
@smithclay - can you tell me which terraform version will feature the fix for this?

Thanks,
Rik

**Comment by smithclay** [comment]
@RSaundersonDeloitte Should be going out (very) shortly in the 0.1.2 release of the New Relic provider.

**Comment by RSaundersonDeloitte** [comment]
@smithclay - amazing, thanks
