### ISSUE TITLE
1.6.0 introduced policy name length restriction

### ISSUE THREAD

**Issue by awcheney** [terraform-providers/terraform-provider-newrelic#199]
### Terraform Version
Terraform v0.11.14
+ provider.aws v2.35.0
+ provider.newrelic v1.6.0

### Affected Resource(s)
- newrelic_alert_policy

### Terraform Configuration Files
```resource "newrelic_alert_policy" "kubernetes" {
  name = "paas-k8s - ${var.cluster_name} - ${var.policy_name}"

  incident_preference = "PER_POLICY"
}
```

### Expected Behavior
`terraform plan` should have worked as it did with the previous version.

### Actual Behavior
```Error: module.cluster_ap-southeast-2_k8s-paas-svc-rua.module.newrelic_policy_system_low.newrelic_alert_policy.kubernetes: expected length of name to be in the range (1 - 64), got paas-k8s - ap-southeast-2.k8s-paas-svc-rua - system - low priority

Error: module.cluster_ap-southeast-2_k8s-paas-test-rua.module.newrelic_policy_system_low.newrelic_alert_policy.kubernetes: expected length of name to be in the range (1 - 64), got paas-k8s - ap-southeast-2.k8s-paas-test-rua - system - low priority

Error: module.cluster_us-west-2_k8s-uat-dev-rua.module.newrelic_policy_system_low.newrelic_alert_policy.kubernetes: expected length of name to be in the range (1 - 64), got paas-k8s - us-west-2.k8s-paas-uat-dev-rua - system - low priority
```

### Steps to Reproduce
With our configuration (with names that are too long):
`terraform plan`

We've pinned the version to 1.5.2 and it's working. It's probably a sensible thing to do (restricting the version) and we will raise tickets to go through and change the names - but would have been nice to have it in the changelog.

**Comment by ctrombley** [comment]
@awcheney Thanks for the report.  We are going to treat this as a bug and loosen the validation.  We have a discrepancy in our [documentation](https://docs.newrelic.com/docs/alerts/new-relic-alerts/rules-limits-glossary/rules-limits-new-relic-alerts) that led us to believe this was a backwards compatible change.
