### ISSUE TITLE
Support for apm key transaction data source

### ISSUE THREAD

**Issue by bridgetlane** [terraform-providers/terraform-provider-newrelic#20]
Currently the only data source able to be used is application, it'd be great if there was also functionality for an apm key transactions data source.

**Comment by paultyng** [comment]
I merged your PR on the API wrapper library and created a new release if you wanted to go for a PR here as well.

**Comment by bridgetlane** [comment]
I will do that, thanks!

**Comment by smithclay** [comment]
Added in #21, thanks @bridgetlane.
