### ISSUE TITLE
Merge SDK in to this repo?

### ISSUE THREAD

**Issue by paultyng** [terraform-providers/terraform-provider-newrelic#25]
The SDK used by this provider (https://github.com/paultyng/go-newrelic) isn't really used outside of this provider, to simplify PR's, maybe it should just be merged in?

**Comment by bridgetlane** [comment]
@paultyng I like this idea. Are there any other providers following that standard?

**Comment by paultyng** [comment]
Ha, I proposed this prior to joining HashiCorp, I think its actually frowned upon, but maybe there is a better org for it to live in, let me ask.

**Comment by paultyng** [comment]
For now I've just added you as a maintainer on that repo as well.
