### ISSUE TITLE
Add documentation on how to prevent always re-creating alerts channels with secrets

### ISSUE THREAD

**Issue by ctrombley** [terraform-providers/terraform-provider-newrelic#269]
Related to https://github.com/terraform-providers/terraform-provider-newrelic/issues/130#issuecomment-562313261.

We should include some notes in the documentation on how to work around constantly re-provisioning alerts channels that contain secrets in their configuration.

**Comment by zlesnr** [comment]
https://github.com/terraform-providers/terraform-provider-newrelic/pull/364
