### ISSUE TITLE
visualization for application_breakdown

### ISSUE THREAD

**Issue by msfidelis** [terraform-providers/terraform-provider-newrelic#271]
I working on some automation monitoring stuff for my SRE team.  I need to use `application_breakdown` visualization on my apps dashboards 

This visualization already enabled on source code. How many time this feature will be released?

https://github.com/terraform-providers/terraform-provider-newrelic/blob/1d6a11b4e230d11f527aa71df51fef160d709ab9/newrelic/structures_newrelic_dashboard.go#L142

```
Error: expected widget.0.visualization to be one of [billboard gauge billboard_comparison facet_bar_chart faceted_line_chart facet_pie_chart facet_table faceted_area_chart heatmap attribute_sheet single_event histogram funnel raw_json event_feed event_table uniques_list line_chart comparison_line_chart markdown metric_line_chart], got application_breakdown

  on ../aws-resources-modules/newrelic_dashboard/newrelic_dashboard.tf line 1, in resource "newrelic_dashboard" "main":
   1: resource "newrelic_dashboard" "main" {

```

Thanks for a nice work on `terraform-provider-newrelic` this is amazing to community!

**Comment by msfidelis** [comment]
![Happy Birthday](https://img.quizur.com/f/img5cd6140cbe5676.94797282.jpg)

**Comment by msfidelis** [comment]
![images (11)](https://user-images.githubusercontent.com/13524134/72027975-b6e58b00-325f-11ea-845f-61ac4cf6937b.jpeg)

**Comment by sanderblue** [comment]
Thanks for reporting this! We should have a fix for this released relatively soon :slightly_smiling_face:
