### ISSUE TITLE
Request for New Relic Monitor Label support

### ISSUE THREAD

**Issue by kooyear** [terraform-providers/terraform-provider-newrelic#274]
Currently, we are using Terraform to deploy New Relic Resources such as Synthetics scripts and Alert policies. We also need to deploy monitor labels (https://docs.newrelic.com/docs/apis/synthetics-rest-api/label-examples/use-synthetics-label-apis#more_help),  but Terraform doesn’t support this feature yet (https://www.terraform.io/docs/providers/newrelic/index.html), Can developers help us to extend the existing Terraform New Relic Provider to support this feature?

**Comment by jthurman42** [comment]
Duplicates #164
