### ISSUE TITLE
APM - support for server-side agent configuration

### ISSUE THREAD

**Issue by Constantin07** [terraform-providers/terraform-provider-newrelic#280]
It would be nice to be able to configure APM server-side agent configuration via terraform rather than doing this via UI.

More details here: https://docs.newrelic.com/docs/agents/manage-apm-agents/configuration/server-side-agent-configuration

This is feature request.

**Comment by jthurman42** [comment]
Agreed, this would be a great enhancement.  Unfortunately, the New Relic APIs do not currently support this ability, so we will not be able to implement in the Terraform provider.  I've created an internal feature request referencing this issue.
