### ISSUE TITLE
Support for Metrics Dashboards

### ISSUE THREAD

**Issue by philiptrovato** [terraform-providers/terraform-provider-newrelic#29]
Love to see support for "Metrics" Dashboards as opposed to just NRQL (Events) type dashboards.

https://docs.newrelic.com/docs/using-new-relic/metrics/analyze-your-metrics/data-collection-metric-timeslice-event-data

**Comment by venki09** [comment]
Yeah I am looking for this enhancement too!

**Comment by venki09** [comment]
Looks like the go-newrelic library that is used to make API calls to newrelic has to be updated to support metric datatype for dashboards. I have a PR out for that https://github.com/paultyng/go-newrelic/pull/62 . Seems like there isn't much activity on that library off-late though 😢

**Comment by ctrombley** [comment]
Addressed in #206
