### ISSUE TITLE
When creating a widget in dashboard with `%` , the attribute `limit` is not pushed to the newrelic

### ISSUE THREAD

**Issue by zacyang** [terraform-providers/terraform-provider-newrelic#290]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version

v0.11.2

### Affected Resource(s)
newrelic_dashboard with JMX metric
e.g `JMX/kafka.consumer/consumer-coordinator-metrics/%/commit-latency-avg`
notice with a '%'

### Terraform Configuration Files
```hcl
resource "newrelic_dashboard" "amplitude-event-dashboard" {
title="test-dashboard"
widget {
    title = "latency"
    duration = 1800000
    notes = "latency"
    visualization = "metric_line_chart"
    entity_ids = [
      "${data.newrelic_application.kakfa_consumer.id}",
    ]
    metric {
      name = "JMX/kafka.consumer/consumer-coordinator-metrics/%/commit-latency-avg"
      values = ["average_response_time"]
    }
    limit = 10
    facet = "host"
    row = 1
    column = 1
  }
}
```

### Debug Output
TF works fine.

### Expected Behavior
The metrics should be retrieved, or the TF plan/apply should fail.

### Actual Behavior
No metrics retrieved, instead of on the dashboard UI from insight

422 response from endpoint https://chartdata.service.newrelic.com/v1/metrics 
```
{"message":"Validation error: 'limit' with 'required when a metric name or scope contains a '%'"}
```

**Comment by ctrombley** [comment]
@zacyang this appears to be an issue with an upstream API and not the Terraform provider.  Would you mind opening an issue with support@newrelic.com so we can triage and track the issue?

**Comment by zlesnr** [comment]
Hi @zacyang, were you able to get in touch with support about this one?

**Comment by zacyang** [comment]
Hi Zach, Newrelic did not confirm wether it is the fault on their side,
they were asking me to do some experiment based on their documentation. I
don't have time to follow this up.
reference for the ticket : https://support.newrelic.com/tickets/384589/

>

**Comment by sanderblue** [comment]
Currently it seems the only workaround for this issue is to use a name without the `%` in the metric name. While attempting to debug this, if I removed the `%` and used `"JMX/kafka.consumer/consumer-coordinator-metrics/commit-latency-avg"` the data for the widget displayed. 

It also appears that your support ticket has been marked as resolved.  

Since this issue is with an upstream API and is outside the scope of this repository, we're closing this issue. Thanks for taking the time to help us and the support team investigate.
