### ISSUE TITLE
Unable to pull app name for Browser only standalone apps

### ISSUE THREAD

**Issue by ESBA-salman** [terraform-providers/terraform-provider-newrelic#306]
Hello,

Is there a way to pull app name for browser only standalone apps?

**Comment by ctrombley** [comment]
Hi @ESBA-salman !  The terraform provider does not currently have a data source for browser applications.  We will be backfilling some feature gaps in the coming weeks, so we will mark this as an enhancement request.

cc @jthurman42 @sanderblue

**Comment by ctrombley** [comment]
Enhancement request tracked in #309.
