### ISSUE TITLE
newrelic_alert_channel for pagerduty not supporting subdomains anymore

### ISSUE THREAD

**Issue by timboven** [terraform-providers/terraform-provider-newrelic#321]
In newrelic_alert_channel the configuration-block is now deprecated and replaced with config.

### Terraform Version
1.12.10

### Affected Resource(s)
- newrelic_alert_channel

### Expected Behavior
Be able to specify the same parameters as before and not only service_key as mentioned in the docs.

### Steps to Reproduce
Try to replace below snippet with a config-variant.

> resource "newrelic_alert_channel" "channel" {
>   name = var.service_name
>   type = "pagerduty"
> 
>   configuration = {
>     subdomain = var.pagerduty_subdomain
>     service_name = pagerduty_service_integration.newrelic_integration.name
>     service_key = pagerduty_service_integration.newrelic_integration.integration_key
>   }
> }

### References
- https://www.terraform.io/docs/providers/newrelic/r/alert_channel.html#pagerduty

**Comment by jthurman42** [comment]
Thank you @timboven for reporting this issue.  Looking through the history of this provider, I do not see any changes to the values required for the PagerDuty integration in the [last three years](https://github.com/terraform-providers/terraform-provider-newrelic/blame/master/newrelic/resource_newrelic_alert_channel.go#L24).

While having these additional attributes did not cause any issues (they were silently ignored), they are not required for configuring [New Relic's PagerDuty notification channel](https://docs.newrelic.com/docs/alerts/new-relic-alerts/managing-notification-channels/notification-channels-control-where-send-alerts#pagerduty).

With the latest release we changed the structure of `config` within the Alert Channels for better validation, thus the unnecessary fields were not included.
