### ISSUE TITLE
infra_process_running does not allow float for threshold value

### ISSUE THREAD

**Issue by prodjito** [terraform-providers/terraform-provider-newrelic#326]
Hello,

The recent float fix is working for infra_metric but not for infra_process_running

### Terraform Version
Terraform v0.11.11

### Affected Resource(s)
-infra_process_running

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
https://drive.google.com/file/d/1R-aCvbQjkQxYFkzWJNcXUTYuCcvNDvz-/view?usp=sharing

### Debug Output
https://gist.github.com/prodjito/804187007f67372a81a04e53aaa73959

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Float should be an acceptable value for critical/warning threshold value

### Actual Behavior
Error out with the message in the gist

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1) Create a "Test Policy TF" alert policy in your New Relic account manually. My script expects this alert policy to already exist.
2) Add an admin API key in the variable.tf files in the infra_metric_alert_condition and infra_process_running_alert_condition directories. Terraform script attached.
3) terraform plan
4) terraform apply
[condition.zip](https://github.com/terraform-providers/terraform-provider-newrelic/files/4079872/condition.zip)

**Comment by jthurman42** [comment]
Simplified config to replicate the issue:

```
provider newrelic { }

# Get an alert policy
resource "newrelic_alert_policy" "alert_policy" {
  name = "Test Policy"
}

# Add critical condition
resource "newrelic_infra_alert_condition" "infra_process_running_critical" {
  policy_id = "${newrelic_alert_policy.alert_policy.id}"

  name        = "Host Zombie Process Count (High)"
  type        = "infra_process_running"
  comparison  = "above"
  where       = "(applicationName = 'MyApp')"
  process_where = "(parentProcessId is null)"

  critical {
    duration      = "5"
    value         = "30.5"
  }
}
```

which causes error:

```
[ERROR] <root>: eval: *terraform.EvalSequence, err: 400 response returned: could not unmarshal condition data ([123 34 99 111 109 112 97 114 105 115 111 110 34 58 34 97 98 111 118 101 34 44 34 99 114 105 116 105 99 97 108 95 116 104 114 101 115 104 111 108 100 34 58 123 34 100 117 114 97 116 105 111 110 95 109 105 110 117 116 101 115 34 58 53 44 34 118 97 108 117 101 34 58 51 48 46 53 125 44 34 101 110 97 98 108 101 100 34 58 116 114 117 101 44 34 110 97 109 101 34 58 34 72 111 115 116 32 90 111 109 98 105 101 32 80 114 111 99 101 115 115 32 67 111 117 110 116 32 40 72 105 103 104 41 34 44 34 112 111 108 105 99 121 95 105 100 34 58 54 49 49 51 54 55 44 34 112 114 111 99 101 115 115 95 119 104 101 114 101 95 99 108 97 117 115 101 34 58 34 40 112 97 114 101 110 116 80 114 111 99 101 115 115 73 100 32 105 115 32 110 117 108 108 41 34 44 34 116 121 112 101 34 58 34 105 110 102 114 97 95 112 114 111 99 101 115 115 95 114 117 110 110 105 110 103 34 44 34 119 104 101 114 101 95 99 108 97 117 115 101 34 58 34 40 97 112 112 108 105 99 97 116 105 111 110 78 97 109 101 32 61 32 39 77 121 65 112 112 39 41 34 125]): json: cannot unmarshal number 30.5 into Go struct field .critical_threshold.value of type int
```

It appears that the unmarshal is attempted to change the JSON into an int, as that is an array of ASCII characters equal to:

```
{"comparison":"above","critical_threshold":{"duration_minutes":5,"value":30.5},"enabled":true,"name":"Host Zombie Process Count (High)","policy_id":611367,"process_where_clause":"(parentProcessId is null)","type":"infra_process_running","where_clause":"(applicationName = 'MyApp')"}
```

**Comment by jthurman42** [comment]
Looking at how we are handling the error (even in the latest master branch), we could definitely report the issue better.  That said, testing through the New Relic UI does not allow for a float for this parameter either, which makes since as you can only have integer count of processes running (30 or 31, but not 30.5 processes).

It appears that the Infra UI returns a 400 and the body contains the data sent that generated the error.  Closing here and tracking in newrelic/newrelic-client-go#108
