### ISSUE TITLE
Alert for Zookeeper Integration does not preview chart

### ISSUE THREAD

**Issue by prodjito** [terraform-providers/terraform-provider-newrelic#337]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.11

### Affected Resource(s)
infra_metric

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
provider "newrelic" {
  api_key = "removed"
  version = "1.11"
}

# Get an alert policy
data "newrelic_alert_policy" "alert_policy" {
  name = "New Relic Professional Services"
}

# Add critical condition
resource "newrelic_infra_alert_condition" "infra_metric_critical" {
  enabled   = "true"
  policy_id = "${data.newrelic_alert_policy.alert_policy.id}"

  name        = "Zookeeper Watch Count (High) - TF"
  type        = "infra_metric"
  integration_provider = "zkSample"
  select      = "zkWatchCount"
  comparison  = "above"
  where       = "(PRODUCT = 'MEETME' AND COMPONENT = 'ZK')"

  critical {
    duration      = "5"
    value         = "90000"
    time_function = "all"
  }
}
```

### Expected Behavior
I created this alert condition manually via the UI. I expect Terraform to create the same thing. Note that the preview chart shows data. https://infrastructure.newrelic.com/accounts/76098/settings/alerts/11392021

### Actual Behavior
This is what Terraform created. Note that not only the preview chart is not showing data, there's the following wording "You selected zkSample as your data source. This cannot be modified in the UI as the integration is not set up. Please use the Infrastructure Alert API to make changes or set up the integration."
https://infrastructure.newrelic.com/accounts/76098/settings/alerts/11392162

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by jthurman42** [comment]
Thanks for reporting the issue.  The expected behavior of the Infrastructure Alerts UI for conditions created through the API is the behavior that you see.  The UI does not allow edits and does not display the preview chart.  This is not an issue with the terraform provider, but the expected UI behavior in the product.  Hopefully this answers your question.  If you'd like to open a feature request on this behavior, please create a support ticket at https://support.newrelic.com explaining the issue.
