### ISSUE TITLE
New policy and condition defaults policy_id to zero instead of <computed>

### ISSUE THREAD

**Issue by kyeah** [terraform-providers/terraform-provider-newrelic#36]
### Terraform Version
0.11.7

### Affected Resource(s)
Of what I've tested:
- newrelic_alert_policy
- newrelic_alert_condition
- newrelic_infra_alert_condition

Possibly a core issue — not familiar with terraform's internals.

### Terraform Configuration Files

A distilled example:

```hcl
resource "newrelic_alert_policy" "app" {
  name = "app"
}

resource "newrelic_infra_alert_condition" "high_cpu_usage" {
  policy_id = "${newrelic_alert_policy.app.id}"

  name          = "High CPU usage"
  type          = "infra_metric"
  event         = "SystemSample"
  select        = "cpuPercent"
  comparison    = "above"

  critical {
    duration      = "2"
    value         = "80"
    time_function = "all"
  }
}
```

### Expected Behavior
The alert condition to be created indicates `policy_id => <computed>`.

### Actual Behavior
The alert condition to be created indicates `policy_id => "0"`:

```
  + newrelic_infra_alert_condition.high_cpu_usage
      id:                       <computed>
      comparison:               "above"
      created_at:               <computed>
      critical.#:               "1"
      critical.0.duration:      "2"
      critical.0.time_function: "all"
      critical.0.value:         "80"
      enabled:                  "true"
      event:                    "SystemSample"
      name:                     "High CPU usage"
      policy_id:                "0"
      select:                   "cpuPercent"
      type:                     "infra_metric"
      updated_at:               <computed>
```

If applied, the creation of the condition fails (since the policy does not exist). On a second `terraform apply`, the policy_id is correct.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
2. `terraform apply` x2 (fails to create the condition the first time, succeeds the second time.)

Any insights welcome here. Thanks!

**Comment by ctrombley** [comment]
This is confirmed working with Terraform v0.12.13 and v1.5.2 of the provider.  Closing.
