### ISSUE TITLE
Support notes for newrelic_dashboard

### ISSUE THREAD

**Issue by phoenixrising87** [terraform-providers/terraform-provider-newrelic#37]
Hey,

I would also like to create notes for a New Relic dashboard. I guess this functionality is not implemented yet. Would be nice to also have support for this :-)

**Comment by ctrombley** [comment]
This issue is blocked on merging https://github.com/paultyng/go-newrelic/pull/61/files.

**Comment by ctrombley** [comment]
Addressed in #206

**Comment by ctrombley** [comment]
Addressed in #206
