### ISSUE TITLE
newrelic_alert_channel PagerDuty resource marked as changed rather than recreated

### ISSUE THREAD

**Issue by stuntbaboon** [terraform-providers/terraform-provider-newrelic#372]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
- 0.11.14
- provider "newrelic" (1.12.2)

### Affected Resource(s)
newrelic_alert_channel

### Terraform Configuration Files
```hcl
resource "newrelic_alert_channel" "alerts_channel_pagerduty" {
  name  = "PagerDuty"
  type  = "pagerduty"

  config {
    service_key = "${data.terraform_remote_state.pagerduty.newrelic_integration_key[0]}"
  }
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

I expected the newrelic_alert_channel resource to be recreated as mentioned in issue - https://github.com/terraform-providers/terraform-provider-newrelic/issues/130 due to the service_key secret.

### Actual Behavior
What actually happened?

An attempt was made to change the newrelic_alert_channel resource and it failed.

Has this behaviour changed in version 1.12.2.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

`terraform apply` of the above configuration results in the following terraform output:

```shell
~ newrelic_alert_channel.eabn_bxf_processing_alerts_channel_pagerduty
      config.0.service_key:         <sensitive> => <sensitive> (attribute changed)

Error: Error applying plan:

1 error occurred:
	* newrelic_alert_channel.alerts_channel_pagerduty: 1 error occurred:
	* newrelic_alert_channel.alerts_channel_pagerduty: doesn't support update
```

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- https://github.com/terraform-providers/terraform-provider-newrelic/issues/130
- https://github.com/terraform-providers/terraform-provider-newrelic/issues/5

**Comment by zlesnr** [comment]
Thank you for the report.  Without digging into the code, I'm not sure if the resource should be changed or  recreated when the configuration changes.  Though, this does look like the same issue in terms of needing to ignore the configuration due to the obscurement of the secrets when they come back from the API.

Perhaps this document would be useful to you, and should be deployed soon.

https://github.com/terraform-providers/terraform-provider-newrelic/pull/364

If that's not the issue you are running into, we can certainly take a closer look, but at first glance, perhaps that resolves your issue.

**Comment by rlmartin** [comment]
Why not edit the provider to delete-recreate the resource? I understand that this would be essentially pointless, but the recommended approach could result in intended changes to be missed. This opens the potential for bugs when your NR setup doesn't match your Terraform. Yes, you could manage the ignoring of this value but, again, bugginess would ensue as people forget that that needs to happen.

**Comment by zlesnr** [comment]
Thank you for the comment.  When I'd initially looked at this, I had the configuration block on the brain, but after talking with the team I see now that this is a bug.  I've put up #387 that should address this issue.
