### ISSUE TITLE
Failiures are hard to debug / missing request log

### ISSUE THREAD

**Issue by viraptor** [terraform-providers/terraform-provider-newrelic#377]
### Terraform Version

Terraform v0.12.12
+ provider.newrelic v1.12.2

### Affected Resource(s)

msa_policy (and possibly others)

### Terraform Configuration Files
```hcl
resource "newrelic_alert_policy" "msa_policy" {
  name = "MSA Alert Policy"
  incident_preference = "PER_POLICY"
}
```

### Debug Output
```
newrelic_alert_policy.msa_policy: Creating...
2020/02/03 16:47:54 [DEBUG] newrelic_alert_policy.msa_policy: applying the planned Create change
2020-02-03T16:47:54.468+1100 [DEBUG] plugin.terraform-provider-newrelic_v1.12.2_x4: 2020/02/03 16:47:54 [INFO] Creating New Relic alert policy MSA Alert Policy
2020/02/03 16:47:56 [DEBUG] newrelic_alert_policy.msa_policy: apply errored, but we're indicating that via the Error pointer rather than returning it: 401 response returned: You do not have privileges to perform this action.
```

### Expected Behavior

The request used should be shown so the issue can be debugged further. (like the s3 provider does for example)
I'm looking at an issue currently where my resources can be queried, but not created (with the admin privileges) and being able to validate the specific requests and which key is used in them would help a lot.

### Actual Behavior
No request in the logs. Debugging is pretty hard.

### Steps to Reproduce
1. `terraform apply`

**Comment by ctrombley** [comment]
We'll investigate this as a bug, since request logging should be available when using `TF_LOG=DEBUG`.

However, we are not currently logging headers, payloads and other potentially sensitive/noisy information.  We'll take that on as an enhancement.

**Comment by ctrombley** [comment]
Debug logging appears to be working as expected.  We will look into adding additional request logging at the `TRACE` level.

**Comment by ctrombley** [comment]
@viraptor Trace-level logging has been added as of [v1.13.0](https://github.com/terraform-providers/terraform-provider-newrelic/releases/tag/v1.13.0).  You can export `TF_LOG=TRACE` to log JSON representations of the request and response bodies along with the HTTP headers.
