### ISSUE TITLE
Drift in newrelic_nrql_alert_condition

### ISSUE THREAD

**Issue by eheydrick** [terraform-providers/terraform-provider-newrelic#379]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

* Provider version 1.12.2
* Terraform 0.12.7

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_nrql_alert_condition`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl

locals {
  thing_error_threshold = {
    stage = {
      warn = 10
      crit = 30
    }
    prod = {
      warn = 2
      crit = 5
    }
  }
}

resource "newrelic_nrql_alert_condition" "thing_exceptions" {
  count       = local.monitor_count
  policy_id   = newrelic_alert_policy.thing[0].id
  name        = "Thing Exceptions"
  runbook_url = local.thing_runbook_url
  enabled     = true

  term {
    duration      = 30
    operator      = "above"
    priority      = "warning"
    threshold     = local.thing_error_threshold[var.environment]["warn"]
    time_function = "any"
  }

  term {
    duration      = 30
    operator      = "above"
    priority      = "critical"
    threshold     = local.thing_error_threshold[var.environment]["crit"]
    time_function = "any"
  }

  nrql {
    query       = "SELECT count(*) FROM TransactionError WHERE appName = 'Thing'"
    since_value = "3"
  }

  value_function = "single_value"
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
No config drift

### Actual Behavior
It wants to change priority and thresholds in the terms even though no change is needed. 

```
# newrelic_nrql_alert_condition.thing_exceptions[0] will be updated in-place
  ~ resource "newrelic_nrql_alert_condition" "thing_exceptions" {
        enabled                      = true
        expected_groups              = 0
        id                           = "4144:88339"
        ignore_overlap               = false
        name                         = "Thing Exceptions"
        policy_id                    = 43443
        type                         = "static"
        value_function               = "single_value"
        violation_time_limit_seconds = 0

        nrql {
            query       = "SELECT count(*) FROM TransactionError WHERE appName = 'Thing'"
            since_value = "3"
        }

      ~ term {
            duration      = 30
            operator      = "above"
          ~ priority      = "critical" -> "warning"
          ~ threshold     = 5 -> 2
            time_function = "any"
        }
      ~ term {
            duration      = 30
            operator      = "above"
          ~ priority      = "warning" -> "critical"
          ~ threshold     = 2 -> 5
            time_function = "any"
        }
    }
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-137 (maybe same issue as this)

**Comment by zlesnr** [comment]
At first glance, this looks like the order of the terms is reversed.  I suspect we need to add a sort somewhere.

**Comment by zlesnr** [comment]
Hmm, I'm not able to reproduce this locally with the manifest given.  The `locals` doesn't have enough of a test for me to build out something locally, but removing the use of `locals` here ends up with an empty plan after a successful apply.  I'm wondering if the data itself is ordering something unexpectedly, but I don't know enough about hash ordering in TF to know off the top of my head.

May I have some of the other relevant details here to reproduce?  Where does `var.environment` come from, and how does that end up creating multiple resources?  Also, the `newrelic_alert_policy.thing[0].id` line doesn't look quite right to me.  What does `newrelic_alert_policy.thing` look like?

**Comment by sanderblue** [comment]
Fixed in #146 

If you come across this bug again, please feel free to open a new issue with steps to reproduce. Thanks for taking the time to report.

**Comment by eheydrick** [comment]
@sanderblue that's for `newrelic_alert_condition` but I'm experiencing this issue with `newrelic_nrql_alert_condition`.

**Comment by sanderblue** [comment]
@eheydrick, my apologies for an incorrect PR reference. I was able to reproduce the issue on version 1.12.2, but I am unable to reproduce it on the latest version of the provider (v1.14.0). Can you give this a try on the latest version and see if you still see the problem?

**Comment by ctrombley** [comment]
@sanderblue I just took a quick look here but it seems like the `term` attribute might deserve a type of `TypeSet` [rather than `TypeList`](https://github.com/terraform-providers/terraform-provider-newrelic/blob/master/newrelic/resource_newrelic_nrql_alert_condition.go#L84).

**Comment by sanderblue** [comment]
That's what we have in the `newrelic_alert_condition` so it would make sense to have them both be the same type. I'll see if that affects anything for `newrelic_nrql_alert_condition`
