### ISSUE TITLE
Synthetics monitor scripts fail to retrieve secure credentials on first run

### ISSUE THREAD

**Issue by tylerrinnan-wf** [terraform-providers/terraform-provider-newrelic#401]
### Terraform Version
v0.12.20

### Affected Resource(s)
- newrelic_synthetics_monitor
- newrelic_synthetics_monitor_script

### Terraform Configuration Files
```hcl
resource "newrelic_synthetics_monitor" "login_availability" {
  name = "Availability Monitor - terraform"
  type = "SCRIPT_BROWSER"
  frequency = 1
  status = "ENABLED"
  locations = ["AWS_US_EAST_1"]
}

data "template_file" "login_script" {
  template = file("${path.module}/login_availability_script.tpl")
  vars = {
    cluster_label="cluster_label",
    domain="domain.com",
    document_id="1234567"
    organization_id="1234567",
    organization_label="organization_label",
    requires_password_action=true,
    secure_username_key="USERNAME"
    secure_password_key="PASSWORD"
  }
}

resource "newrelic_synthetics_monitor_script" "login_availability_monitor_script" {
  monitor_id = newrelic_synthetics_monitor.login_availability.id
  text = data.template_file.login_script.rendered
}

```
**Please note: I have obfuscated sensitive data for the purposes of this bug ticket.**

### Debug Output
https://gist.github.com/tylerrinnan-wf/f91cae298ad4b3898d2e1074212ad2b6 
**Please note: I have obfuscated sensitive data for the purposes of this bug ticket.**

### Expected Behavior
Monitor should successfully create and append monitor script. First run within defined monitor interval should be successful (barring any test failures within the script).

### Actual Behavior
Both the `newrelic_synthetics_monitor` and `newrelic_synthetics_monitor_script` resources are created without any noticeable error from the CLI. The first run from the scripted monitor fails because the script (only on first run), returns 'UNDEFINED' for credentials retrieved from New Relic's secure credential storage. This does not happen if the monitor is created manually. Please see important factoids below where I have included my conversation with New Relic support on this issue.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
- I'm reaching out as a follow up to this New Relic support ticket: https://gist.github.com/tylerrinnan-wf/bfda47a4e61824180942c217103e3003
- If i run `terraform apply` with just the `newrelic_synthetics_monitor` resource and then proceed to uncomment out the `newrelic_synthetics_monitor_script` and run another `terraform apply` the issue in which the script is unable to access the secure credential store (on first run) is alleviated.
- I'm wondering if there needs to be more time between the two resource creations for these resources to be created and run without error.

### References

Thanks for taking a look. I'm unsure if this is entirely a bug with the provider as the debug logs _seem_ to be making two separate calls for each resource. It may be a race condition.

**Comment by sanderblue** [comment]
Thanks for the detailed report. We'll take a look and will report back.

**Comment by sanderblue** [comment]
@tylerrinnan-wf, since `newrelic_synthetics_monitor_script` seems to depend on `newrelic_synthetics_monitor` in this case, you could use Terraform's meta-argument [`depends_on`](https://www.terraform.io/docs/configuration/resources.html#meta-arguments) to let Terraform know about the dependency. Could you give that a try and let us know if that works for you?
