### ISSUE TITLE
Base newrelic api golang library

### ISSUE THREAD

**Issue by jufemaiz** [terraform-providers/terraform-provider-newrelic#41]
Hi there,
Just reviewing the newrelic provider to undertaken some further development and I'm wanting to know of Hashicorp / Community perspectives on the newrelic provider options.

At the moment the provider is using https://github.com/paultyng/go-newrelic/ however that has no build checks to ensure that the library is stable.

https://github.com/yfronto/newrelic is older by a few months and with better docs.

Was there a design decision in adoping paultyng/go-newrelic ? If so, should I look to PR into that project (including getting automated testing with travis, README.md etc)?

Cheers!

**Comment by ctrombley** [comment]
@jufemaiz , [go-newrelic](https://github.com/paultyng/go-newrelic/) is the SDK we will continue to use at this time in the provider.  The library does have a test suite and is using Travis CI to ensure that no regressions are introduced as PRs are merged. This decision may change in the future, but for now the path forward is to make PRs into that library if you need additional functionality.
