### ISSUE TITLE
newrelic_dashboard bug when run in Linux for long integer filling

### ISSUE THREAD

**Issue by kooyear** [terraform-providers/terraform-provider-newrelic#418]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.12.13

### Affected Resource(s)
Please list the resources as a list, for example:
- newrelic_dashboard

Error as below
```
[0m
[0m[0m
[31m
[1m[31mError: [0m[0m[1mwidget.8.end_time: must be a whole number, got 1.580944938e+12[0m

[0m  on ../modules/resources/dashboards.tf line 1, in resource "newrelic_dashboard" "dashboards":
   1: resource "newrelic_dashboard" "dashboards" [4m{[0m
[0m
[0m[0m
[31m
[1m[31mError: [0m[0m[1mwidget.8.duration: must be a whole number, got 2.6784e+09[0m

```

when I try to run Terraform in Linux, I need to fill "end_time" with 1580944938000, and run `terraform plan`, I got the error above. but when I run on my mac, no this problem. it seems that the linux convert 1580944938000 to 1.580944938e+12n and cannot be detected as right number

**Comment by jthurman42** [comment]
Thanks @kooyear for the report.  Can you provide an example HCL that is causing this issue?

**Comment by kooyear** [comment]
@jthurman42   at the ```resource "newrelic_dashboard"``` in the ```widget``` block
```
      duration       =  widget.value.duration == null ? null : floor(widget.value.duration)
      end_time       =  widget.value.end_time == null ? null : floor(widget.value.end_time)
```

the input variables which is exported from the New Relic console with API, value as below
```
                    "duration": 2678400000,
                    "end_time": 1580944938000,
```

**Comment by kooyear** [comment]
@ctrombley Hi, Does it mean that is an existing bug?

**Comment by ctrombley** [comment]
@kooyear The label addition was categorizing the issue for our workflow.

**Comment by zlesnr** [comment]
In trying to reproduce this, I think I've not got enough information.  Can you provide an example HCL that demonstrates this please?

I'm currently looking at the following, but duration and end_time show up as `0` in the state file.

```terraform
resource "newrelic_dashboard" "printer" {
  title = "test"
  icon = "pie-chart"
  visibility = "all"
  editable = "editable_by_all"

  widget {
    title = "Print]"
    visualization = "facet_pie_chart"
    nrql = "SELECT uniqueCount(id) FROM FEED"
    row = 1
    column = 1
  }
}
```

**Comment by kooyear** [comment]
@zlesnr Hi Zash, if you try to create a `widget` with `visualization = "metric_line_chart"`, `duration` will be a required value, but `end_time` is still optional. The bug we found is in `visualization = "metric_line_chart"`, it that kind of visualization, you can set 
```
"duration": 2678400000,
"end_time": 1580944938000` 
```
to reproduce the issue I have, example HCL as below
```
 resource "newrelic_dashboard" "dashboards" {
  title ="test"
  icon       = "bar-chart"
  visibility = "all"
  editable   ="editable_by_all"
  widget {
      title         = "title"
      visualization = "metric_line_chart"

      row           = 1
      column        = 1

      width         =  1
      height         =  1

      entity_ids     =  [
                        431804671
                    ]

      
     metric {
        name = "WebFrontend/QueueTime"
        values = [ "average_call_time" ]
    }

      duration       =  2678400000
      end_time       =  1580944938000


  }

}
```
And with `metric_line_chart` type, `metric` and `entity_ids` are also required, based on the documentation https://www.terraform.io/docs/providers/newrelic/r/dashboard.html#metric_line_chart 

the value I gave is from our environment, I think when you test, you need to create relative values first.
Please test run Terraform apply in Linux environment, based on our experience, the same script works properly in Mac os, but fail in Ubuntu:18.04

**Comment by zlesnr** [comment]
I was able to get the HCL you've given above running in a docker container to try and reproduce the issue, but I'm able to create and update the resource without trouble.

This is using `Terraform v0.12.24` and `go version go1.14.1 linux/amd64` and `Linux 1a26af982ff4 4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019 x86_64 Linux`.

I don't know what else would cause this here.  Is there perhaps a locale I should try?  What version of Go are you using?  Which linux?

I'm using the following docker container.
```
FROM golang:alpine
MAINTAINER "HashiCorp Terraform Team <terraform@hashicorp.com>"

ENV TERRAFORM_VERSION=0.12.24

RUN apk add --update git bash openssh

ENV TF_DEV=true
ENV TF_RELEASE=true

WORKDIR $GOPATH/src/github.com/hashicorp/terraform
RUN git clone https://github.com/hashicorp/terraform.git ./ && \
    git checkout v${TERRAFORM_VERSION} && \
    /bin/bash scripts/build.sh

WORKDIR $GOPATH/src/github.com/terraform-providers/terraform-provider-newrelic

RUN git clone https://github.com/terraform-providers/terraform-provider-newrelic.git ./ && \
    go build -o terraform-provider-newrelic

WORKDIR $GOPATH

RUN mkdir localbind

ENTRYPOINT ["bash"]
```

And then tested with the following.
```
docker build . -t terraform-provider/newrelic:zleslie
docker run -it \
    -e "NEW_RELIC_REGION" \
    -e "NEW_RELIC_API_KEY" \
    -e "NEW_RELIC_ADMIN_API_KEY" \
    -e "NEW_RELIC_ACCOUNT_ID" \
    -e "NEWRELIC_REGION" \
    -e "NEWRELIC_API_KEY" \
    -e "NEWRELIC_ADMIN_API_KEY" \
    -e "NEWRELIC_PERSONAL_API_KEY" \
    -e "NEWRELIC_ACCOUNT_ID" \
    -v ~/go/src/github.com/terraform-providers/terraform-provider-newrelic:/go/localbind \
    terraform-provider/newrelic:zleslie
```

You probably wouldn't' need to use the `-v` here, but I was expecting to make changes to the provider here.

**Comment by kooyear** [comment]
@zlesnr  Hi, thank you for your reply, Linux is `ubuntu:18.04` , `Linux dse-monitoring-bamboo-ag-68-9hvtr 3.10.0-957.43.1.el7.x86_64 #1 SMP Thu Dec 5 05:10:53 EST 2019 x86_64 x86_64 x86_64 GNU/Linux`, Terraform version is `Terraform v0.12.13`, and it seems that I didn't install golang in my Docker, I still can run terraform without golang. and I used local plugins, which are from  https://releases.hashicorp.com/terraform-provider-newrelic/1.14.0/terraform-provider-newrelic_1.14.0_linux_386.zip and https://releases.hashicorp.com/terraform-provider-template/2.1.2/terraform-provider-template_2.1.2_linux_386.zip.

Do you think that might be an old Terraform version problem? 

I can try to update to the same version as yours to test. I will let you know later.
