### ISSUE TITLE
Alerts and conditions: APM external service implementation

### ISSUE THREAD

**Issue by doctornkz** [terraform-providers/terraform-provider-newrelic#437]
Hello! 
Thank you for your time and enthusiasm to support community and improving New Relic provider. 
I'd like to know is `apm_external_service` condition is supported? 
I've read documentation https://www.terraform.io/docs/providers/newrelic/ and `grep -r` the source code but nothing there. 
REST API reference : https://docs.newrelic.com/docs/alerts/rest-api-alerts/new-relic-alerts-rest-api/rest-api-calls-new-relic-alerts#ext-services-conditions
Feel free to point me to right issue or discussion if my way is incorrect.
Thank you!

**Comment by ctrombley** [comment]
@doctornkz Externam service conditions are not yet supported in the Terraform provider.  I'll add this as an enhancement request to our backlog.

**Comment by ctrombley** [comment]
Related to #442.
