### ISSUE TITLE
request: add name output to newrelic_synthetics_monitor

### ISSUE THREAD

**Issue by nwsparks** [terraform-providers/terraform-provider-newrelic#453]
Hello, feature request for adding name output to `newrelic_synthetics_monitor`.

The reason for this is that it would help in loop scenarios, see below:

```
resource "newrelic_synthetics_monitor" "ping_monitor" {
  count = length(var.urls_to_monitor)
  name = "${var.name} ${var.urls_to_monitor[count.index]}"
  type = "SIMPLE"
  frequency = 5 #minutes
  status = "ENABLED"
  locations = ["AWS_US_EAST_1", "AWS_US_EAST_2", "AWS_US_WEST_1"]

  uri                       = var.urls_to_monitor[count.index]
  validation_string         = "{\"api\":\"GOOD\",\"database\":\"GOOD\"}"
  verify_ssl                = true
  bypass_head_request       = true
}

resource "newrelic_synthetics_alert_condition" "alert" {
  count = length(newrelic_synthetics_monitor.ping_monitor)
  policy_id = newrelic_alert_policy.critical.id

  name        = ""
  monitor_id  = newrelic_synthetics_monitor.ping_monitor[count.index].id
}
```

Without being able to reference the name from `resource "newrelic_synthetics_monitor" "ping_monitor"` it is difficult to name the alert condition in a meaningful way as I can't associate the ID with the name of the monitor.

**Comment by zlesnr** [comment]
Hi, thanks for raising an issue.  I think I'm unclear on the ask here.  Are you saying that `newrelic_synthetics_monitor.ping_monitor[count.index].name` doesn't work currently?

**Comment by nwsparks** [comment]
@zlesnr sorry I guess I should have tested it, I had checked https://www.terraform.io/docs/providers/newrelic/r/synthetics_monitor.html#attributes-reference and did not see name as an exported attribute. `newrelic_synthetics_monitor.ping_monitor[count.index].name` does seem to work though so I will close this.

appreciate the quick reply.
