### ISSUE TITLE
synthetics in EU doesn't work

### ISSUE THREAD

**Issue by hieuln** [terraform-providers/terraform-provider-newrelic#468]
### Terraform Version
terraform -v
Terraform v0.11.14
+ provider.newrelic v1.15.0

### Affected Resource(s)
- newrelic_synthetics_monitor

### Terraform Configuration Files
$ cat main.tf
provider "newrelic" {
  api_key       = "${var.new_relic_api_key_dev}"
  api_url       = "https://api.eu.newrelic.com/v2"
  infra_api_url = "https://infra-api.eu.newrelic.com/v2"
}

resource "newrelic_synthetics_monitor" "example" {
  name      = "example-test1"
  type      = "SIMPLE"
  frequency = 5
  status    = "ENABLED"
  locations = ["AWS_EU_CENTRAL_1"]
  uri       = "https://www.google.com"
}
variable "new_relic_api_key_dev" {}

### Expected Behavior
newrelic_synthetics_monitor.example is created

### Actual Behavior
1 error occurred:
        * newrelic_synthetics_monitor.example: 1 error occurred:
        * newrelic_synthetics_monitor.example: 401 response returned: HTTP 401 Unauthorized

### Steps to Reproduce
1. `terraform apply`

To make sure the key is good, this command return good result:

curl -X GET 'https://api.eu.newrelic.com/v2/applications.json' -H "X-Api-Key:${TF_VAR_new_relic_api_key_dev}" -i

Other resource works, for example newrelic_alert_policy

**Comment by jthurman42** [comment]
@hieuln Thank you for reporting the issue.  Currently Synthetics monitors require setting of an additional URL for the EU region, similar to Infrastructure (documented [here](https://www.terraform.io/docs/providers/newrelic/index.html#synthetics_api_url)).  Please add the following:

```
provider "newrelic" {
  api_key = "${var.new_relic_api_key_dev}"
  api_url = "https://api.eu.newrelic.com/v2"
  infra_api_url = "https://infra-api.eu.newrelic.com/v2"
  # New line to add:
  synthetics_api_url = "https://synthetics.eu.newrelic.com/synthetics/api/v3"
}
```

If you have any further configuration issues, please create a thread on our support forum here: https://discuss.newrelic.com/c/build-on-new-relic/developer-toolkit . Thanks!
