### ISSUE TITLE
[newrelic_dashboard] Autofill of "row" / "column" fields for widgets

### ISSUE THREAD

**Issue by ilya40umov** [terraform-providers/terraform-provider-newrelic#495]
Hey Folks,

Basically, I've got a dashboard with 15 rows (each having 3 widgets) which is created via the terraform provider. And every time I need to insert/remove a new row in the middle, I need to update all "row" fields that are below the affected row (which is quite tedious and error-prone). I'm even starting to think that I should just write a python script to update the rows for me... 

The bottom line: it would be really nice if I could just give the newrelic_dashboard an array of widgets and it would figure out the rows (and maybe columns) automatically.

**Comment by zlesnr** [comment]
Apologies for the slow response here.  We all chatted about this a couple weeks ago, but nobody got back to you.  Having been in that seat before, I agree it's pretty tedious to update a bunch of widgets.  Unfortunately, I think this is the normal state of things for this API.

On the bright side, the new dashboard API should be coming to help enable a smoother experience, though I don't know what shape that will take to know for sure if it won't also have the same grid issues.

Though, I do wonder, if you left a little room between your rows, would it help give you the breathing room you require?  I don't actually know if the API would support this or not, but if you start with row 1, and then the net row would be row 11, and then 21 and so on.  In this way, perhaps you could leave yourself room to insert a row without having to modify the rows near by.  If you end up testing this, I'd love to know if it works.

**Comment by sanderblue** [comment]
I wonder if you could utilize Terraform's configuration [variables](https://www.terraform.io/docs/configuration-0-11/variables.html) and use some [math](https://www.terraform.io/docs/configuration/expressions.html#arithmetic-operators) within each widget to calculate the row and column values based on some config variable(s).

**Comment by msilverm-web** [comment]
I did something like this which was successful where you are creating dynamic number of rows based on a list of things you want to display...  it's working great..  You can then do math for the follow-on rows...   

 dynamic "widget"  {
    for_each = var.integrations
    content {
        title = "${widget.value.integration} Average Response Time"
        visualization = "metric_line_chart"
        duration = var.tsapp_response_duration
        entity_ids = [
          data.newrelic_application.tsapp.id
        ]
        metric {
          name = "External/${widget.value.integration}/all"
          values = [ "average_response_time", "max_response_time" ]
        }
        row = 3 + widget.value.index
        column = 1
    }
  }

**Comment by ouranos** [comment]
Yeah I'm using a similar pattern:
```
 dynamic "widget" {
    for_each = var.queues

    content {
      title         = "Queue Length (name:${widget.value})"
      duration      = 1800000
      visualization = "metric_line_chart"
      
      ...

      row    = 4 + floor(widget.key / 3) # 3 widgets per rows, starting at row 4
      column = 1 + widget.key % 3        # 3 widgets per rows
    }
  }
```

**Comment by sanderblue** [comment]
Thanks for the additional examples. Dynamic widget adjustments definitely look feasible.

@ilya40umov were you able to resolve your issue based on some of the examples provided here?

**Comment by ilya40umov** [comment]
Hey Folks, thanks for the examples and sorry for the delay!

We are using terraform 0.11.x right now for the monitoring and I'm not sure I'll be able to migrate to 0.12 as the repo has gozillion terraform files that all need to be checked. So, I won't be able to test `dynamic`  with `for_each`.

Additionally, since all widgets on the dashboard has different tiles/visualization types/nrql etc. it would mean that I'll need to have a list of objects having all of these fields, that I'll need to iterate. Sounds doable, but I'm not sure if my colleagues would appreciate maintaining all these afterwards.

I was honestly hoping we could get something like these eventually (we are using SFx as well, and their I define the charts separately and then refer them by id when creating the dashboard):
https://www.terraform.io/docs/providers/signalfx/r/dashboard.html#grid-1

**Comment by zlesnr** [comment]
Hi @ilya40umov, Looking over the signalfx provider, the separation between widget and dashboard is interesting, but for my own education, don't you still run into the issue of needing to know the width since its still specified in the dashbaord?  What am I not seeing there that makes that provider easier to work with here?
