### ISSUE TITLE
Add outlier and baseline as threshold type to nrql alerts

### ISSUE THREAD

**Issue by hingstarne** [terraform-providers/terraform-provider-newrelic#50]
At the moment of writing the only thresholds that are configurable in the provider are fixed numbers.
Would be great to have the baseline like mentioned [here](https://docs.newrelic.com/docs/alerts/new-relic-alerts/defining-conditions/create-baseline-alert-conditions) as a threshold type.
Are there any plans to add this feature?

**Comment by bridgetlane** [comment]
@hingstarne I do not know of any but feel free to PR the functionality to this repo! Otherwise mark this issue as 'help wanted' so one of our contributors can get to it at some point if able.

**Comment by hingstarne** [comment]
@bridgetlane Thank you for the response. I cannot add labels to an issue, so if you would be so kind to at the help wanted flag?

**Comment by bridgetlane** [comment]
@hingstarne yes, done!

**Comment by rahulwa** [comment]
I don't think New Relic have API for that, as from this doc:
https://docs.newrelic.com/docs/alerts/rest-api-alerts/new-relic-alerts-rest-api/rest-api-calls-new-relic-alerts#conditions-nrql

**Comment by ctrombley** [comment]
Outliers have been addressed in #141, and as @rahulwa mentions, there is a feature gap in New Relic's underlying APIs that don't allow us to create baseline alerts currently.  We will revisit this if the gap is filled in the future.
