### ISSUE TITLE
newrelic_nrql_alert_condition operator for outlier detecting drift when there is none

### ISSUE THREAD

**Issue by grantc** [terraform-providers/terraform-provider-newrelic#506]
When running a plan against a newrelic_nrql_alert_condition that uses the ```outlier``` type subsequent plans show a config drift when no changes have occurred.

### Terraform Version

```
Terraform v0.12.24
+ provider.newrelic v1.16.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- newrelic_nrql_alert_condition

### Terraform Configuration Files
```hcl
provider "newrelic" {
  version = "~> 1.15"
}

resource "newrelic_alert_policy" "ac_test" {
  name                = "Alert Condition Test"
  incident_preference = "PER_CONDITION"
}

resource "newrelic_nrql_alert_condition" "api_gateway_latency" {
  policy_id      = newrelic_alert_policy.ac_test.id
  name           = "API Gateway Latency"
  enabled        = true
  ignore_overlap = true

  term {
    duration      = 30
    priority      = "critical"
    threshold     = "2000"
    time_function = "all"
  }

  nrql {
    query       = "SELECT sum('provider.latency.average') FROM ApiGatewaySample FACET displayName"
    since_value = "3"
  }

  value_function  = "single_value"
  type            = "outlier"
  expected_groups = 1
}

```

### Debug Output

https://gist.github.com/grantc/ceb4b9c2acbfd8f473a72090287273b8

### Expected Behavior

No changes detected

### Actual Behavior

```An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # newrelic_nrql_alert_condition.api_gateway_latency will be updated in-place
  ~ resource "newrelic_nrql_alert_condition" "api_gateway_latency" {
        enabled                      = true
        expected_groups              = 1
        id                           = "693904:13209245"
        ignore_overlap               = true
        name                         = "API Gateway Latency"
        policy_id                    = 693904
        type                         = "outlier"
        value_function               = "single_value"
        violation_time_limit_seconds = 0

        nrql {
            query       = "SELECT sum('provider.latency.average') FROM ApiGatewaySample FACET displayName"
            since_value = "3"
        }

      - term {
          - duration      = 30 -> null
          - operator      = "above" -> null
          - priority      = "critical" -> null
          - threshold     = 2000 -> null
          - time_function = "all" -> null
        }
      + term {
          + duration      = 30
          + operator      = "equal"
          + priority      = "critical"
          + threshold     = 2000
          + time_function = "all"
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

If I set the ```operator``` to ```above``` then no changes are detected.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`
1. `terraform plan`
1. `terraform apply`
1. `terraform plan`

### Important Factoids

None

### References

Appears to be similar to terraform-providers/terraform-provider-newrelic#379 but it's still occurring in the latest version of the provider

**Comment by zlesnr** [comment]
Thank you for raising the issue.  I'm able to reproduce the issue here with the manifest you've provided on v1.16.0.  Next I'll test on the latest (unreleased) master version, since there are some changes waiting to go out in this area of the code.

**Comment by zlesnr** [comment]
This looks to be a bug in the client not properly handling all available operator types.  Can you confirm, that if you set the `operator` to either `above` or `below` on the given term that you get no drift?

**Comment by zlesnr** [comment]
Try setting the operator to "above".  It seems that when working with outliers, the api will only accept "above" as a valid attribute, but the resource defaults to "equal", which is not acceptable for outliers, and the response is forced to use "above".

**Comment by grantc** [comment]
Thanks - that's the option we went with.
