### ISSUE TITLE
support to update application settings

### ISSUE THREAD

**Issue by bharathkumarna** [terraform-providers/terraform-provider-newrelic#52]
We would need support to update certain parameters of apm application.

reference: https://rpm.newrelic.com/api/explore/applications/update

**Comment by ctrombley** [comment]
This will require changes to the [underlying SDK](https://github.com/paultyng/go-newrelic/blob/master/api/applications.go).

**Comment by jthurman42** [comment]
Upstream library now supports updates, unblocking this: https://github.com/newrelic/newrelic-client-go/blob/master/pkg/apm/applications.go#L110

**Comment by zlesnr** [comment]
I've started this work, but based on the new client.  https://github.com/terraform-providers/terraform-provider-newrelic/pull/449 adds support for the new client.  v0.15.0 of the new client is ready for update.
