### ISSUE TITLE
Widgets dimensions on NR1 Dashboards are not correct

### ISSUE THREAD

**Issue by ronster37** [terraform-providers/terraform-provider-newrelic#523]
# Terraform Version
Terraform v0.12.24
+ provider.newrelic v1.16.0

### Affected Resource(s)
- newrelic_dashboard

### Terraform Configuration Files
```hcl
resource "newrelic_dashboard" "dashboard" {
  title = "heroku metrics"

  widget {
    title = "CPU"
    visualization = "line_chart"
    nrql = "SELECT average(`sample#load_avg_1m`) AS 'Load avg 1m', average(`sample#load_avg_5m`) AS 'Load avg 5m', average(`sample#load_avg_15m`) AS 'Load avg 15m' FROM Log WHERE appname = '${var.app_name}' TIMESERIES SINCE 1800 seconds ago"
    row = 1
    column = 1
    width = 6
    height = 3
  }

  widget {
    title = "Memory"
    visualization = "line_chart"
    nrql = "SELECT average(`sample#memory_quota`) AS 'Memory Quota', average(`sample#memory_total`) AS 'Memory Total' FROM Log WHERE appname = '${var.app_name}' TIMESERIES SINCE 1800 seconds ago"
    row = 1
    column = 7
    width = 6
    height = 3
  }

  widget {
    title = ""
    visualization = "markdown"
    source = <<EOF
[What is an acceptable amount of Dyno load?](https://help.heroku.com/88G3XLA6/what-is-an-acceptable-amount-of-dyno-load)
EOF
    row = 4
    column = 3
    width = 6
    height = 1
  }
}

```

### Expected Behavior
What should have happened?
<img width="1434" alt="Screen Shot 2020-04-22 at 11 05 00 AM" src="https://user-images.githubusercontent.com/2498495/80017435-7665f200-8489-11ea-8550-e16ca39977e7.png">

### Actual Behavior
What actually happened?
<img width="1435" alt="Screen Shot 2020-04-22 at 11 05 38 AM" src="https://user-images.githubusercontent.com/2498495/80017521-93022a00-8489-11ea-9026-2a37dfc022aa.png">

It may be because the `newrelic_dashboard` does not support NR1 dashboards yet? In any case, after doing some testing I figured out width of the grid with NR1 is 12. However when I apply a dashboard with the correct dimensions the widgets are huge. I follow it up with another `terraform apply` and it says there are no changes to apply. I then resize the dashboard manually to look like the expected behavior. Follow that up with another `terraform apply` and it says there are no changes to apply. It may be because this resources does not yet support NR1 but because it does create the NR1 dashboard it should also honor that grid system as well. NR1 dashboards are much better than the insights ones and would prefer to use those.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. terraform apply

**Comment by sanderblue** [comment]
@ronster37  This feature is now available in the latest release (1.17.1) For more information, please see the updated [docs](https://www.terraform.io/docs/providers/newrelic/r/dashboard.html#grid_column_count) for using the `grid_column_count` attribute to help organize your grid. 🙂
