### ISSUE TITLE
version 1.17 version causing error during Terraform Apply - newrelic_nrql_alert_condition

### ISSUE THREAD

**Issue by HugoMarks** [terraform-providers/terraform-provider-newrelic#547]
### Terraform Version
0.12.24

### Affected Resource(s)
newrelic_nrql_alert_condition

### Terraform Configuration Files
terraform {
  required_version = ">= 0.12"
}

provider "newrelic" {
  api_key = var.newrelic_api_key
  version = "~> 1.15"
}

resource "newrelic_nrql_alert_condition" "nrql" {
  policy_id = var.policy
  name = var.name
  enabled = var.enabled
  count = var.use_warning ? 0 : 1

  term {
    duration = var.critical_duration
    operator = var.critical_operator
    priority = var.critical_priority
    threshold = var.critical_threshold
    time_function = "all"
  }

  nrql {
    query = var.query
    since_value = "15"
  }
  value_function = "single_value"
  runbook_url = var.team_name
}

### Debug Output
https://gist.github.com/HugoMarks/2eb6def55e4d23cb8dc67927b2d2f70c

### Expected Behavior
Creating alerts successfully

### Actual Behavior
Error: Provider produced inconsistent result after apply

### Steps to Reproduce
Create several alerts with resource X and run the terraform apply command.

**Comment by HugoMarks** [comment]
workaround is to pin the version of the terraform provider for new relic to 1.16.0

**Comment by jthurman42** [comment]
Likely duplicate of #544
