### ISSUE TITLE
Modifying an alert policy recreates resource

### ISSUE THREAD

**Issue by ianrayns** [terraform-providers/terraform-provider-newrelic#55]
### Terraform Version
0.11.8

### Affected Resource(s)
- newrelic_alert_policy

### Terraform Configuration Files
Initial config
```hcl
resource "newrelic_alert_policy" "policy" {
  name                = "Alert Policy"
}
```
Update alert policy
```hcl
resource "newrelic_alert_policy" "policy" {
  name                = "Alert Policy"
  incident_preference = "PER_CONDITION_AND_TARGET"
}
```
### Expected Behavior
Alert policy should be updated

### Actual Behavior
Alert policy is recreated, losing all created alert conditions

**Comment by sgsiebers** [comment]
I think this can be closed now
