### ISSUE TITLE
Update github.com/hashicorp/terraform-plugin-sdk version and handle deprecations

### ISSUE THREAD

**Issue by zlesnr** [terraform-providers/terraform-provider-newrelic#560]
Currently this code is running behind the latest 1.x version of the SDK.  In the logs, we can see that there are several data type notes about deprecations and such.  We should work towards updating to the latest version and resolve whatever deprecations are necessary.

The changes that need to be addressed for the 1.x are captured in the upstream change log.

https://github.com/hashicorp/terraform-plugin-sdk/blob/v1-maint/CHANGELOG.md

Once updated, perhaps the transition to the 2.x SDK will be simpler.

**Comment by ctrombley** [comment]
This has been done in v1.18.0 of the provider.  There's no replacement for `GetOkExists` currently, and it will not be removed until there is a suitable replacement.  The deprecation was intended to prevent further usage of the method in provider development.  For those reasons, the linter errors have just been suppressed.
