### ISSUE TITLE
Terraform won't remove `runbook_url` from `newrelic_alert_condition`

### ISSUE THREAD

**Issue by DarthVanger** [terraform-providers/terraform-provider-newrelic#563]
### Terraform Version
```
$ terraform -v
Terraform v0.12.24
+ provider.newrelic v1.16.0
```

### Affected Resource(s)
- `newrelic_alert_condition`

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    newrelic = "1.16.0"
  }
}

data "newrelic_application" "app" {
  name = "testapp"
}

resource "newrelic_alert_policy" "foo" {
  name = "test terraform runbook url"
}

resource "newrelic_alert_condition" "foo" {
  policy_id = newrelic_alert_policy.foo.id

  name        = "foo"
  type        = "apm_app_metric"
  entities    = [data.newrelic_application.app.id]
  metric      = "apdex"
  runbook_url = "https://www.example.com"
  condition_scope = "application"

  term {
    duration      = 5
    operator      = "below"
    priority      = "critical"
    threshold     = "0.75"
    time_function = "all"
  }
}
```

### Expected Behavior
Removing `runbook_url` from `newrelic_alert_condition` should remove it from NewRelic and update terraform state accordingly.

### Actual Behavior
Removing `runbook_url` from `newrelic_alert_condition` results in `terraform apply` saying it has removed it, but in fact it remains untouched in NewRelic and in `terraform.tfstate`.

Running `terraform apply` again results in the same behavior repeated: it says it will remove `runbook_url`, then says changes applied successfully.

`terraform apply` can be run many times, it never says "Infrastructure is up to date".

### Steps to Reproduce
1. Copy code from [`alert_condition` usage example](https://www.terraform.io/docs/providers/newrelic/r/alert_condition.html#example-usage).
2. Run it. It will create an alert condition with `runbook_url = "https://www.example.com"`.
3. Remove `runbook_url = "https://www.example.com"` from `main.tf`
4. Run `terraform apply`. It will say it will remove the `runbook_url`

    ```
    Resource actions are indicated with the following symbols:
      ~ update in-place

    Terraform will perform the following actions:

      # newrelic_alert_condition.foo will be updated in-place
      ~ resource "newrelic_alert_condition" "foo" {
          [...]
          - runbook_url           = "https://www.example.com" -> null
          [...]
      }

    Plan: 0 to add, 1 to change, 0 to destroy.

    newrelic_alert_condition.foo: Modifying... [id=741096:13502385]
    newrelic_alert_condition.foo: Modifications complete after 2s [id=741096:13502385]

    Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
    ```
5. Check NewRelic: the runbook url is still there.
6. Run `terraform apply` again. It will again say it will remove the `runbook_url`

    ```
    Resource actions are indicated with the following symbols:
      ~ update in-place
      # newrelic_alert_condition.foo will be updated in-place
      ~ resource "newrelic_alert_condition" "foo" {
          [...]
          - runbook_url           = "https://www.example.com" -> null
          [...]
      }

    Plan: 0 to add, 1 to change, 0 to destroy.

    newrelic_alert_condition.foo: Modifying... [id=741096:13502385]
    newrelic_alert_condition.foo: Modifications complete after 1s [id=741096:13502385]

    Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
    ```
7. Still no changes in NewRelic, running `apply` again will always say it will remove the url, but it never does.

**Comment by ctrombley** [comment]
Hey @DarthVanger, I was able to reproduce and I'm working on a fix now.

**Comment by ctrombley** [comment]
@DarthVanger This has been fixed in [v1.18.0 of the provider](https://github.com/terraform-providers/terraform-provider-newrelic/releases/tag/v1.18.0).  Give it a try and let us know if you have any issues.

**Comment by DarthVanger** [comment]
@ctrombley thanks, seems to work now!
Why haven't you listed the bug fix in the release notes though? :)

**Comment by jthurman42** [comment]
Thanks for confirming the fix.  Sorry we missed it in the change log. The issue was resolved in an [upstream library](https://github.com/newrelic/newrelic-client-go/pull/302), and that didn't make it into the provider change log.  I've updated the release notes to include it now, and will add it to the CHANGELOG.md file.
