### ISSUE TITLE
Synthetics Monitor Type Query

### ISSUE THREAD

**Issue by selvan1978** [terraform-providers/terraform-provider-newrelic#590]
**Terraform Version**

Terraform v0.12.24

**NewRelic Proider Version**

provider.newrelic v1.18.0

**Affected Resource(s)**

newrelic_synthetics_monitor

**Issue**

I am using monitor type as "SIMPLE". Is there any possibility to use "PING" as a monitor type instead of "SIMPLE"?

Thanks,
Selvan.

**Comment by sanderblue** [comment]
@selvan1978 thanks for the question, and I can understand how this could be misleading. 

The monitor type of "Ping" is specified with `SIMPLE` in the API - i.e. if you're wanting to use the "Ping" type, using `SIMPLE` in your configuration should work just fine.

Check out the [documentation](https://docs.newrelic.com/docs/apis/synthetics-rest-api/monitor-examples/manage-synthetics-monitors-rest-api) for more information on how the type names map to the API names.

Note: We typically advise posting questions on discuss.newrelic.com and prefer GitHub issues for bug reports and feature requests.

**Comment by selvan1978** [comment]
Thanks for your help. I got it.
