### ISSUE TITLE
Query regarding newrelic synthetics label

### ISSUE THREAD

**Issue by selvan1978** [terraform-providers/terraform-provider-newrelic#591]
**Terraform Version**

Terraform v0.12.24

**NewRelic Proider Version**

provider.newrelic v1.18.0

**Affected Resource(s)**

newrelic_synthetics_label

**Terraform Configuration Files**

resource "newrelic_synthetics_label" "test" {
  monitor_id = newrelic_synthetics_monitor.testmonitor.id
  type = "MyCategory-1"
  value = "MyValue-1"
}

**Issue**

Please confirm if we can create monitoring label like below. As of now we can give one type and value in the code.

Mycategory1:MyValue-1 Mycategory2:MyValue-2 Mycategory2:MyValue-2 

Thanks,
Selvan.

**Comment by sanderblue** [comment]
Hi @selvan1978,  you can use Terraform's [`count`](https://www.terraform.io/docs/configuration/resources.html#count-multiple-resource-instances-by-count) expression to accomplish this (see example below). Let us know if this works for you. 🙂 

Example:

```hcl
variable "labels" {
  type = list
  default = [
    {
      type  = "category-1"
      value = "value-1"
    },
    {
      type  = "category-1"
      value = "value-2"
    },
    {
      type  = "category-2"
      value = "value-3"
    },
    {
      type  = "category-2"
      value = "value-4"
    },
  ]
}

resource "newrelic_synthetics_label" "test" {
  count = length(var.labels)

  monitor_id = newrelic_synthetics_monitor.testmonitor.id
  type           = var.labels[count.index].type
  value         = var.labels[count.index].value
}
```
Note: We typically advise posting questions on [discuss.newrelic.com](https://discuss.newrelic.com/c/build-on-new-relic/developer-toolkit) and prefer GitHub issues for bug reports and feature requests.

**Comment by selvan1978** [comment]
Thanks for your reply. I will try this option.
