### ISSUE TITLE
Getting timeout error in Jenkins pipeline using terraform code for synthetics monitor

### ISSUE THREAD

**Issue by selvan1978** [terraform-providers/terraform-provider-newrelic#592]
**Terraform Version**

Terraform v0.12.24

**NewRelic Proider Version**

provider.newrelic v1.18.0

**Affected Resource(s)**

newrelic_synthetics_monitor

**Terraform Configuration Files**

resource "newrelic_synthetics_monitor" "testmonitor" {
  name = "test"
  type = "SIMPLE"
  frequency = 5
  status = "ENABLED"
  locations = ["AWS_US_EAST_1", "AWS_US_EAST_2"]
  uri                       = "https://example.com"  
  validation_string         = "success"
}

**Issue**

I have setup newrelic monitoring using terraform and pipeline job configured in Jenkins. Resource creation working fine but when we execute the job second time without changes in the code, refreshing state throwing errors (Ideally it should show “No changes. Infrastructure is up-to-date” message). Jenkins server configured in cloud environment. I am facing this issue both windows based jenkins and linux based jenkins.

Error: GET https://synthetics.newrelic.com/synthetics/api/v4/monitors/ giving up after 4 attempts
Error: GET https://synthetics.newrelic.com/synthetics/api/v4/monitors/ giving up after 4 attempts

Note: Same code working fine in my local jenkins (Windows based) and terraform command line.

Thanks,
Selvan.

**Comment by sanderblue** [comment]
@selvan1978 I am unable to reproduce this. It sounds like a potential issue with the Jenkins environment or possibly an issue with the Synthetics API. Could something in your Jenkins environment be causing this? You can also update your `terraform apply` to be `TF_LOG=trace terraform apply` to see a more verbose logging output. This could help identify the actual error that's happening with the HTTP request.

**Comment by selvan1978** [comment]
Thanks for your reply. I will try to get verbose logging output

**Comment by selvan1978** [comment]
I have enabled the trace and noticed below errors in the logs.

**Error Logs:**

2020/05/21 11:39:04 [ERROR] : eval: *terraform.EvalRefresh, err: GET https://synthetics.newrelic.com/synthetics/api/v4/monitors/2ce45bd5-f98a-4c4a-b703-111114b920a9 giving up after 4 attempts
2020/05/21 11:39:04 [ERROR] : eval: *terraform.EvalSequence, err: GET https://synthetics.newrelic.com/synthetics/api/v4/monitors/2ce45bd5-f98a-4c4a-b703-111114b920a9 giving up after 4 attempts

2020/05/21 11:39:31 [TRACE] vertex “provider.newrelic (close)”: evaluating
2020/05/21 11:39:31 [TRACE] [walkRefresh] Entering eval tree: provider.newrelic (close)
2020/05/21 11:39:31 [TRACE] : eval: *terraform.EvalCloseProvider
2020/05/21 11:39:31 [TRACE] GRPCProvider: Close
2020-05-21T11:39:31.499Z [DEBUG] plugin: plugin process exited: path=/var/jenkins_home/workspace/wdms-amg-newrelic-infra/.terraform/plugins/linux_amd64/terraform-provider-newrelic_v1.18.0_x4 pid=1769
2020-05-21T11:39:31.499Z [DEBUG] plugin: plugin exited
2020/05/21 11:39:31 [TRACE] [walkRefresh] Exiting eval tree: provider.newrelic (close)
2020/05/21 11:39:31 [TRACE] vertex “provider.newrelic (close)”: visit complete
2020/05/21 11:39:31 [TRACE] dag/walk: upstream of “root” errored, so skipping
2020/05/21 11:39:31 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2020/05/21 11:39:31 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock

Error: GET https://synthetics.newrelic.com/synthetics/api/v4/monitors/2ce45bd5-f98a-4c4a-b703-111114b920a9 giving up after 4 attempts

2020-05-21T11:39:31.503Z [DEBUG] plugin: plugin process exited: path=/var/jenkins_home/workspace/wdms-amg-newrelic-infra/.terraform/plugins/linux_amd64/terraform-provider-newrelic_v1.18.0_x4 pid=1761
2020-05-21T11:39:31.503Z [DEBUG] plugin: plugin exited
[Pipeline] }
[Pipeline] // ansiColor
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Terraform Apply)
Stage “Terraform Apply” skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE

**Comment by sanderblue** [comment]
Hmm, the trace is still missing the actual HTTP request logs that display the request and response bodies (you will need to redact your API key from that section of the logs). 

I would try making that particular request manually with `curl` to see if that works. 
```
curl -v -H 'X-Api-Key:YOUR_NEW_RELIC_ADMIN_API_KEY' https://synthetics.newrelic.com/synthetics/api/v4/monitors/2ce45bd5-f98a-4c4a-b703-111114b920a9
```
If this works, then there is likely something going on within the Jenkins environment that's causing the error, such an a missing environment variable or potentially an invalid API key. The Synthetics API requires your [New Relic Admin API key](https://docs.newrelic.com/docs/apis/get-started/intro-apis/types-new-relic-api-keys#admin)

**Comment by zlesnr** [comment]
Is there perhaps a proxy in the way?  That timeout indicates a failure to reach the API.  I've seen this in local development, when I have HTTP_PROXY set, but the proxy isn't running.

**Comment by selvan1978** [comment]
I have already tried below curl command and able to access the API without any issues. I am facing this issue in Jenkins which is configured in cloud (linux/windows). 

curl -v -H 'X-Api-Key:YOUR_NEW_RELIC_ADMIN_API_KEY' https://synthetics.newrelic.com/synthetics/api/v4/monitors/2ce45bd5-f98a-4c4a-b703-111114b920a9

Looks like this issue is not related to invalid API key as resources are creating successfully in the first time execution using same NewRelic Admin API key but when we execute the job second time (without any changes in the code in the code), refreshing state throwing errors (Ideally it should show “No changes. Infrastructure is up-to-date” message). 

I dont see this issue in my local jenkins (Windows based) OR terraform command line.

**Comment by jthurman42** [comment]
Since it appears that you are able to run the command directly with Terraform, and on your local Jenkins instance, this would not be an issue with the provider.  It must be an issue with the hosted Jenkins environment configuration.  Since you are able to run a cURL command without issue, it could be an invalid proxy environment variable, which the provider would automatically detect and use.  Can you list out the environment variables (names, not values) that contain `PROXY`, or ensure that they are unset and test?  Without knowledge of your specific environment that the provider is running in, there isn't much more that we can do to assist.

**Comment by pickgr** [comment]
Just a quick note that I saw similar errors when hitting the synthetics API using another CI/CD system (automation). NewRelic support confirmed that they actually rate limit this API and suggested reducing the frequency of requests to 3 per second or less.  Unfortunately, at this time there is no way to increase this limit.
