### ISSUE TITLE
Alert policy creation date is 50,000 years in the future

### ISSUE THREAD

**Issue by skyzyx** [terraform-providers/terraform-provider-newrelic#610]
### Terraform Version

```
Terraform v0.12.26
+ provider.newrelic v1.18.0
```

### Affected Resource(s)

* [newrelic_alert_policy](https://www.terraform.io/docs/providers/newrelic/r/alert_policy.html)

### Terraform Configuration Files

```hcl
# https://www.terraform.io/docs/providers/newrelic/r/alert_policy.html
resource "newrelic_alert_policy" "ops" {
  incident_preference = "PER_CONDITION"
  name                = "Testing"
}

output "policy_ops" {
  value = newrelic_alert_policy.ops
}
```

### Debug Output

https://gist.github.com/skyzyx/a80928a32f6f7f35ddb79ed182973fe9

### Expected Behavior

When reviewing the `output` from Terraform, the date-stamps should be accurate.

```hcl
policy_ops = {
  "created_at" = "2020-05-27T21:44:31-08:00"
  "id" = "824543"
  "incident_preference" = "PER_CONDITION"
  "name" = "Testing"
  "updated_at" = "2020-05-27T06:22:14-08:00"
}
```

### Actual Behavior

The date-stamp is more than 50,000 years in the future.

```hcl
policy_ops = {
  "created_at" = "52374-09-06T21:44:31-08:00"
  "id" = "824543"
  "incident_preference" = "PER_CONDITION"
  "name" = "Testing"
  "updated_at" = "52374-09-28T06:22:14-08:00"
}
```

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. `terraform apply`. The execution should complete without error.

1. Review the output variable in the Terminal.

**Comment by jthurman42** [comment]
Thanks for reporting the issue.

I've tracked this back to a custom EpochTime type in the underlying library, and opened an issue against it: newrelic/newrelic-client-go#328

**Note:** Both of these fields on Alert Policy are **DEPRECATED** and will be removed from the next major release of the provider (2.x)

**Comment by jthurman42** [comment]
This will be resolved in the next release.
