### ISSUE TITLE
Applying twice with small changes between runs results in multiple sets of resources instead of a single, updated set

### ISSUE THREAD

**Issue by skyzyx** [terraform-providers/terraform-provider-newrelic#614]
### Terraform Version

```
Terraform v0.12.26
+ provider.newrelic v1.18.0
```

### Affected Resource(s)

* [newrelic_alert_policy](https://www.terraform.io/docs/providers/newrelic/r/alert_policy.html)
* [newrelic_infra_alert_condition](https://www.terraform.io/docs/providers/newrelic/r/infra_alert_condition.html)

### Terraform Configuration Files

Nothing too complicated. One `newrelic_alert_policy` with two `newrelic_infra_alert_condition` resources.

```hcl
# https://www.terraform.io/docs/providers/newrelic/r/alert_policy.html
resource "newrelic_alert_policy" "ops" {
  incident_preference = "PER_CONDITION"
  name                = "testing"
}

# https://www.terraform.io/docs/providers/newrelic/r/infra_alert_condition.html
resource "newrelic_infra_alert_condition" "cond_ec2_instance_cpu" {
  name    = "EC2 Instance CPU"
  enabled = true

  # Bind this condition to the following alert policy
  policy_id = newrelic_alert_policy.ops.id

  # Type of metric and where to read it from
  type       = "infra_metric"
  event      = "SystemSample"
  select     = "cpuPercent"
  comparison = "above"
  where      = "( `ec2Tag_Service` = '${local.tag_service}' )"

  # WARN
  warning {
    value         = 80
    duration      = 10
    time_function = "all"
  }

  # CRIT
  critical {
    value         = 90
    duration      = 10
    time_function = "all"
  }

  # Hours until it auto-closes
  violation_close_timer = 1
}

# https://www.terraform.io/docs/providers/newrelic/r/infra_alert_condition.html
resource "newrelic_infra_alert_condition" "cond_ec2_instance_disk_usage" {
  name    = "EC2 High Disk Usage"
  enabled = true

  # Bind this condition to the following alert policy
  policy_id = newrelic_alert_policy.ops.id

  # Type of metric and where to read it from
  type       = "infra_metric"
  event      = "SystemSample"
  select     = "diskUsedPercent"
  comparison = "above"
  where      = "( `ec2Tag_Service` = '${local.tag_service}' )"

  # WARN
  warning {
    value         = 80
    duration      = 10
    time_function = "all"
  }

  # CRIT
  critical {
    value         = 90
    duration      = 10
    time_function = "all"
  }

  # Hours until it auto-closes
  violation_close_timer = 1
}
```

### Debug Output

This is the log for my _actual_ project, which is a more complete version of the easier-ro-run Terraform above.

https://gist.github.com/skyzyx/48a7699cad5ef114fd2ac007086c139f

### Steps to Reproduce

1. Write Terraform which includes a [newrelic_alert_policy](https://www.terraform.io/docs/providers/newrelic/r/alert_policy.html) resource and one or more [newrelic_infra_alert_condition](https://www.terraform.io/docs/providers/newrelic/r/infra_alert_condition.html) resources.

1. `terraform apply`.

1. Add an additional [newrelic_infra_alert_condition](https://www.terraform.io/docs/providers/newrelic/r/infra_alert_condition.html) resource to your project, but make no other changes (e.g., alert names, Terraform resource names).

1. `terraform apply`.

### Expected Behavior

The second `terraform apply` will *update* the resources created by the first `terraform apply`.

There will be **one** [newrelic_alert_policy](https://www.terraform.io/docs/providers/newrelic/r/alert_policy.html) resource, with the same number of [newrelic_infra_alert_condition](https://www.terraform.io/docs/providers/newrelic/r/infra_alert_condition.html) resources as you executed in the second `terraform apply`.

See “[Principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment)”.

### Actual Behavior

The second `terraform apply` creates a **second set** of resources _in addition to_ those created by the first `terraform apply`.

There are now **two** [newrelic_alert_policy](https://www.terraform.io/docs/providers/newrelic/r/alert_policy.html) resources — the first with the same number of [newrelic_infra_alert_condition](https://www.terraform.io/docs/providers/newrelic/r/infra_alert_condition.html) resources as you executed in the first `terraform apply`, and a the second with the same number of [newrelic_infra_alert_condition](https://www.terraform.io/docs/providers/newrelic/r/infra_alert_condition.html) resources as you executed in the second `terraform apply`.

<img width="1471" alt="Screen Shot 2020-05-28 at 10 11 43 PM" src="https://user-images.githubusercontent.com/39447/83231826-fc3c2380-a140-11ea-96f6-b968cf7bef8f.png">

Additionally, running `terraform apply` twice with _no changes_ in-between does not result in two sets of policies and conditions.

**Comment by zlesnr** [comment]
Hi, thank you for the report.  With just the two resources provided built from the version mentioned, I'm not seeing duplicates created.  But I see in the logs a policy channel that is being updated.  Is that a manifest update being enforced, or is that the issue you're pointing at that is causing the duplication?

**Comment by skyzyx** [comment]
From what I've been seeing:

1. Applying `newrelic_alert_policy` and one `newrelic_infra_alert_condition`.
1. Subsequently, applying the same `newrelic_alert_policy` and both `newrelic_infra_alert_condition` resources.

To be clear, this is on _update_, not _creation_. In a fairly-controlled environment, I'm seeing duplicates get created.

Can you confirm?

**Comment by zlesnr** [comment]
I've tried many times now to get the behavior you're seeing, but I'm still not seeing duplicates.  I suspect there is something more nuance going on here.  I've tried updating one condition, while the second one is being created, or destroyed.  Destroying one, and then the other, and then re-enabling them in different orders.  Each time, the results in the UI reflect the state of the code after an apply.  Other than the specific strings that you have provided and a different policy name, I'm using the resources you provided.  Can you confirm that the above resources do indeed reflect the behavior you are seeing in your production environments?

**Comment by skyzyx** [comment]
@zlesnr: OK, thank you for confirming. I just got off a call with @jthurman42, and will try again to replicate this on my end in the next couple of days. If I can't replicate it, I'll close the ticket.

Thanks!

**Comment by zlesnr** [comment]
Thanks @skyzyx, Anything to help me reproduce theissue would get me started tracing down any bugs.

**Comment by skyzyx** [comment]
I haven't had time to review this, but with the information that things are moving towards NRQL alerts anyway, I'm planning to convert my existing alerts and I know I don't see the issue with those.

Resolving.

**Comment by zlesnr** [comment]
If you see the issue again, by all means reopen or re-file.
