### ISSUE TITLE
newrelic_nrql_alert_condition output; term as map instead of list

### ISSUE THREAD

**Issue by skyzyx** [terraform-providers/terraform-provider-newrelic#631]
### Feature Description

I'm writing a Terraform module, then writing integration tests for that module using [Terratest](https://terratest.gruntwork.io).

#### Module

I have some module code wherein I output an _object_ representing a resource.

```hcl
resource "newrelic_nrql_alert_condition" "cond_alb_5xx_errors" {
  nrql {
    query       = "FROM LoadBalancerSample SELECT average(provider.httpCodeTarget5XXCount.Sum) WHERE label.Service = '${local.tag_service}'"
    since_value = "3" # Evaluation offset
  }

  # WARN
  term {
    priority      = "warning"
    operator      = "above"
    threshold     = var.cond_alb_5xx_errors_warn
    time_function = "any" # at least once in
    duration      = var.cond_alb_5xx_errors_over_minutes
  }

  # CRIT
  term {
    priority      = "critical"
    operator      = "above"
    threshold     = var.cond_alb_5xx_errors_crit
    time_function = "any" # at least once in
    duration      = var.cond_alb_5xx_errors_over_minutes
  }

  # Snip...
}

output "cond_alb_5xx_errors" {
  value = newrelic_nrql_alert_condition.cond_alb_5xx_errors
}
```

#### Test + calling Terraform

I have a `test.tf` file and a `test.go` file. In the `test.tf` file, I call that module and run it. I then have to output data from this file to make it available to the Terratest code in `test.go` (essentially, one level of abstraction).

```hcl
module "nri_alerts" {
  source = "..."

  slack_channel_name = "..."
  slack_webhook_url  = "..."
  runbook_url        = "..."
  tags               = [...]
}

output "cond_alb_5xx_errors_nrql" {
  value = newrelic_nrql_alert_condition.cond_alb_5xx_errors.nrql
}

output "cond_alb_5xx_errors_term" {
  value = newrelic_nrql_alert_condition.cond_alb_5xx_errors.term
}
```

#### Reading the output

The data from the `nrql` node is an array of objects:

```
[
  {...}
]
```

The data from the `term` node is expected to be an array of objects, but Terraform calls it a "set":

```
[
  {...},
  {...}
]
```

Whereas I can access `nrql[0]`, I cannot access `term[0]`. Instead, I needed to convert the _set_ to a _list_.

```hcl
output "cond_alb_5xx_errors_term" {
  value = tolist(newrelic_nrql_alert_condition.cond_alb_5xx_errors.term)[0]
}
```

This particular inconsistency _may_ be construed as a bug, but this is a lesser issue than the following:

Additionally, I would love to be able to know which `term` index is _critical_ vs _warning_. Right now, I'm observing that _critical_ is consistently at `[0]` and _warning_ is consistently at `[1]` — which is alphabetical, but I have no way of knowing if this is part of the Terraform _software contract_ and whether or not I can rely on it.

In the end, I have an output like this, which I can test for in Terratest:

```hcl
output "cond_alb_5xx_errors_term_warning_priority" {
  value = module.nri_alerts.cond_alb_5xx_errors.term[1].priority
}
```

```golang
value := terraform.Output(t, terraformOptions, "cond_alb_5xx_errors_term_warning_priority")
assert.Equal(t, "warning", value)
```

I would prefer something more concrete like:

```hcl
output "cond_alb_5xx_errors_term_warning_priority" {
  value = module.nri_alerts.cond_alb_5xx_errors.warning.priority
}
```

An array would make sense if the list of `term` blocks were infinite… or at least repeatable (e.g., multiple "critical" terms), but AFAICT the priorities are actually an enum of `[critical, warning]` wherein a single `term` of each priority is allowed.

If this were true, changing `term[1]` to `warning` (or whatever) would both simplify the output expressions, as well as make it easier to look up a specific known output value without having to iterate over the objects to find the right one. I.e., having this be a map instead of a list.

**Comment by zlesnr** [comment]
It seems that the Set type is not ordered, so relying on the index after you convert it to a list might be a little squirrelly. 

https://www.terraform.io/docs/extend/schemas/schema-types.html#typeset

Further, it looks like the `tolist` function in use above won't guarantee any additional ordering from the already unordered set.

https://www.terraform.io/docs/configuration/functions/tolist.html

We could just remove `terms` altogether, and replace it with `critical` and `warning` which would look a lot like a term, just without the priority and would get you what you are after.

**Comment by skyzyx** [comment]
That would be great. Thank you!

**Comment by zlesnr** [comment]
I've started working in this direction.  I'll try to have something to show for it this week.
