### ISSUE TITLE
Support entity tagging

### ISSUE THREAD

**Issue by ctrombley** [terraform-providers/terraform-provider-newrelic#656]
### Objective
Create an entity tag resource and data source.

**Comment by imsathyakumar** [comment]
Without tag support via Terraform, we are unable to de-clutter our Synthetics tests between projects. 

And the below is not working anymore :
https://www.terraform.io/docs/providers/newrelic/r/synthetics_label.html

**Comment by ctrombley** [comment]
Resolved by #679
