### ISSUE TITLE
Support for New Relic One Tags in Replacement of Synthetic Labels

### ISSUE THREAD

**Issue by MAN98** [terraform-providers/terraform-provider-newrelic#666]
### Feature Description
New Relic will be retiring Synthetic Labels in favor of New Relic One Tags and currently the TF New Relic Provider does not have a resource for New Relic One Tags. 

### Describe Alternatives
I reckon when Synthetic Labels are applied after the end of life the TF APPLY will fail. So my plan at least for my code base is to comment-out the Synthetic Label resources.

### Additional context
As of today, New Relic Synthetic Labels End Of Life Date is July 20, 2020.

**Comment by jthurman42** [comment]
We are currently working on a Provider v2.x, and should have an initial beta release out in the next few weeks.  That release will add Entities / Entity tags and should resolve this as well.  The issue for adding tag support is #656

**Comment by zlesnr** [comment]
Thanks for keeping an eye out @MAN98.

**Comment by ctrombley** [comment]
Related to #672 .

**Comment by ctrombley** [comment]
Resolved by #679
