### ISSUE TITLE
Cannot import dashboard - x509 cert error

### ISSUE THREAD

**Issue by tscully49** [terraform-providers/terraform-provider-newrelic#671]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://discuss.newrelic.com/c/build-on-new-relic/developer-toolkit

### Terraform Version
Terraform v0.12.26
+ provider.newrelic v1.18.0 _(and 1.19)_

### Affected Resource(s)
Please list the resources as a list, for example:
- newrelic_dashboard

### Terraform Configuration Files

Note: This is a base resource, I am just trying to import the state to this resource so I can edit the resource and match it 1:1.

```hcl
resource "newrelic_dashboard" "production_dashboard" {
  title = "New Relic Terraform Example"

  filter {
    event_types = [
        "Transaction"
    ]
    attributes = [
        "appName",
        "name"
    ]
  }
}
```

### Debug Output

Note: Using 1234567 as dummy value, replacing true value.

```
newrelic_dashboard.production_dashboard: Importing from ID "1234567"...
newrelic_dashboard.production_dashboard: Import prepared!
  Prepared newrelic_dashboard for import
newrelic_dashboard.production_dashboard: Refreshing state... [id=1234567]

Error: Get https://api.newrelic.com/v2/dashboards/1234567.json: x509: certificate signed by unknown authority
```

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
The state of the dashboard should have been imported.

### Actual Behavior
An error was thrown and the state was not imported.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `AWS_PROFILE=xxxxx terraform import newrelic_dashboard.production_dashboard 1234567`

### Important Factoids
I can curl the dashboard URL from my command line and receive valid json just fine.  Other terraform providers are also working fine at the moment.  This is the only time I am receiving this error.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

**Comment by tscully49** [comment]
When I threw a `sudo` in front of the import call it ended up working.  Any thoughts on why that might be would be appreciated, thanks!

**Comment by zlesnr** [comment]
That probably has something to do with the regular user not knowing how to find the CA bundle on the system.  Either permission protected directory, or something injected into the environment by sudo, which you would see in your sudoers file.  Just a guess.  I'll close the issue since it sounds like you have a resolution.
