### ISSUE TITLE
Can I put in api_key from a vault file without hardcoding it? If so, how?

### ISSUE THREAD

**Issue by sarahfiona1** [terraform-providers/terraform-provider-newrelic#69]
I have tried:

# Configure the New Relic provider
provider "newrelic" {
  api_key = "${var.newrelic_api_key}"
}

variable "newrelic_api_key" {
  default = "..."
}

# "${data.terraform_remote_state.monitoring.newrelic_api_vault}"  ---- default cannot have interpolation syntax

Could I do it using a token in the provider?

**Comment by ctrombley** [comment]
@sarahfiona1 , the `NEWRELIC_API_KEY` environment variable can be used to set the api key when running terraform commands:

```
NEWRELIC_API_KEY=<VALID_API_KEY> terraform apply
```
