### ISSUE TITLE
Support for newrelic_alert_condition of type "NRQL QUERY"

### ISSUE THREAD

**Issue by RubyLi0612** [terraform-providers/terraform-provider-newrelic#8]
### Terraform Version

Terraform v0.9.8

### Affected Resource(s)

newrelic_alert_condition

![screen shot 2017-06-22 at 5 29 08 pm](https://user-images.githubusercontent.com/29551647/27492229-565f2288-57fa-11e7-9631-be69d952398c.png)

### Terraform Configuration Files
```hcl
# Configure the New Relic provider
provider "newrelic" {
  api_key = "${var.newrelic_api_key}"
}

# Create an alert policy to apply for different objects
resource "newrelic_alert_policy" "alert" {
  name = "General_Alert"
}
```

### Expected Behavior
Support for type "NRQL QUERY"
```hcl
# Add condition 
resource "condition" "foo" {
  policy_id = "${newrelic_alert_policy.foo.id}"

  name        = "bar"

  term {
    duration      = 60
    operator      = "above"
    priority      = "critical"
    threshold     = "0"
    time_function = "all"
  }

  nrql {
    query = "SELECT count(*) from SyntheticCheck where monitorName = 'foo' and result != 'SUCCESS'"
    since_value = 3
  }

  value_fuinction = single_value
}
```

### Actual Behavior
Type is not supported. There is no for alarm condition type option and other corresponding data source types for NRQL QUERY.

### Important Factoids
See https://github.com/hashicorp/terraform/blob/950e24bc049bfaa6858fec2e09e38ab857cbfddf/builtin/providers/newrelic/resource_newrelic_alert_condition.go#L13
for types.
Similar enhancement issue seen in https://github.com/hashicorp/terraform/issues/13516 for another alarming type

**Comment by buraks** [comment]
This would be a nice feature to have!

**Comment by MattSurabian** [comment]
Can this be closed since https://www.terraform.io/docs/providers/newrelic/r/nrql_alert_condition.html exists?

**Comment by ctrombley** [comment]
Closing this, since support now exists for the `newrelic_nrql_alert_condition` resource.
